### ISSUE TITLE
Mobile browser issues

### ISSUE THREAD

**Issue by adamghill** [adamghill/django-unicorn#102]
There are some issues on mobile.

- Brave Browser Mobile Android 8.0.1
- Chrome mobile

From: https://old.reddit.com/r/django/comments/kjamxv/full_stack_framework_for_django/ggx53ee/

**Comment by adamghill** [comment]
Sounds like the homepage todo fails, but the example works: https://old.reddit.com/r/django/comments/kjamxv/full_stack_framework_for_django/ggx5eoq/. 

Might be related to validation?

**Comment by adamghill** [comment]
Desktop browser issue as well: 
- Chrome latest version (87.0.4280.88 ) on OSX Catalina latest build

From: https://old.reddit.com/r/django/comments/kjamxv/full_stack_framework_for_django/ggx6600/

**Comment by casdr** [comment]
I'm getting CSRF related issues on Firefox:

![image](https://user-images.githubusercontent.com/7041290/103105855-c1479300-4630-11eb-805a-2dd98596e233.png)

Request Headers:
![image](https://user-images.githubusercontent.com/7041290/103105862-d9b7ad80-4630-11eb-9f30-7bdd1d321d2c.png)

**Comment by adamghill** [comment]
I get the CSRF token here: https://github.com/adamghill/django-unicorn/blob/master/django_unicorn/static/js/utils.js#L63. I currently look for the cookie and the hidden input, but maybe that is failing for certain browsers. I wonder if I should check look in the X-CSRFToken header, as well.

**Comment by casdr** [comment]
Weird, after opening the same page in the same browser now, the cookie has been set. However, when I open the same page in an incognito session, I'm getting the same issue again.

In my case, the response of the page itself doesn't contain any Set-Cookie headers:
![image](https://user-images.githubusercontent.com/7041290/103106676-bb08e500-4637-11eb-84ae-eb500e0c0f81.png)

**Comment by adamghill** [comment]
Interesting! Ok, now I know how to reproduce this issue (I see the 403 in a Firefox incognito window, as well) so that's awesome. :)

Hopefully I can figure out a fix relatively quickly. Thanks for the detailed information!

**Comment by casdr** [comment]
Caching seems to be the issue: https://docs.djangoproject.com/en/2.1/ref/csrf/#caching

**Comment by adamghill** [comment]
I just deployed the site and removed all of `cache_page` decorators from the views. It seems to work for me incognito in Firefox now. Can you double-check to see if it seems to be working for you now?

**Comment by casdr** [comment]
Works great here!

**Comment by adamghill** [comment]
I asked multiple users on /r/django to test to make sure the fix worked and it seemed to.

Following the recommendation in https://docs.djangoproject.com/en/3.1/ref/csrf/#caching, I just re-enabled caching, but made sure to generate the CSRF token on pages I know require it with https://github.com/adamghill/django-unicorn.com/commit/7b07e65813ca36a1fe4adbccc93f58c5698d83f6.

Tested it with an incognito window in Firefox and everything still seems to work fine. Closing this issue!
