### ISSUE TITLE
Unable to install Django-unicorn due to orjson on windows 

### ISSUE THREAD

**Issue by casper1403** [adamghill/django-unicorn#105]
Hi, I tried to install django-unicorn with pip but was unable to do so because of its dependency on orjson. 

    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python37-32\python.exe' 'c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\user\AppData\Local\Temp\tmp44sdrpnu'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-ykiwhtsu\orjson_635ea463d23b456bb448742a00ed7258
    Complete output (6 lines):

    Cargo, the Rust package manager, is not installed or is not on PATH.
    This package requires Rust and Cargo to compile extensions. Install it through
    the system's package manager or via https://rustup.rs/

    Checking for Rust toolchain....

I tried to install Rust and Cargo but this failed as it was not compatible with my 32-bit python interpreter. I succeeded my install by using an anaconda environment and first using "conda install -c conda-forge orjson" , "conda install pip" and then "pip install django-unicorn". You might want to look into this as it took me a couple of hours to work around this error. 

**I tried poetry as well which gave the same error

**Comment by adamghill** [comment]
I'm sorry you ran into those issues. I'm investigating the issues on the `orison` GitHub repo to understand what support it has on Windows, but maybe the best thing would be if I created some documentation around installation problems so it is at least documented?

Another approach would be to move away from `orjson` to a pure-Python JSON parser, but that would require a non-trivial amount of work. :(

**Comment by adamghill** [comment]
Reading through https://github.com/ijl/orjson/issues/19 and seeing `c:\users\user\appdata\local\programs\python\python37-32\python.exe` I'm guessing it was a 32-bit install of Python on your Windows machine? I can make a note of the lack of support for 32-bit Windows because of the `orison` dependency in the documentation.

**Comment by casper1403** [comment]
Good point. I will try to change my kernel to 64 bit and update you on any changes

**Comment by casper1403** [comment]
Yess so I changed my Python installation to the 64 bit version and was able to install django-unicorn without any problems! Just adding this to the installation page in the docs would be sufficient.

**Comment by adamghill** [comment]
That's awesome, I'm glad it was relatively straight-forward to get it installed. I made a note in the docs and am deploying them now.
