### ISSUE TITLE
Django-Unicorn Website: Problem with Examples

### ISSUE THREAD

**Issue by psyonara** [adamghill/django-unicorn#112]
When I try out the examples on the Django-Unicorn website, some of them behave strangely. The count, search, and validation examples display this behaviour: as I am typing, the input is cleared automatically after a second or so.

![unicorn_search](https://user-images.githubusercontent.com/771840/103894683-f0153d00-50f7-11eb-9b73-a272ec0d899b.gif)

OS: Ubuntu 20.04
Browser: Vivaldi 3.5.2115.81 (Stable channel) (64-bit)

@adamghill You said that you can't reproduce this, so maybe it's a browser issue...

**Comment by adamghill** [comment]
Thanks for reporting this! Can you also include a screenshot of any console output (if any) and a gif of the network panel traffic for XHR in the dev toolbar?

I can't reproduce on Vivaldi on MacOS. This is an example:
![Jan-08-2021 23-22-07](https://user-images.githubusercontent.com/317045/104082965-7f117a80-5208-11eb-8bbe-f8a5672f446d.gif)

I'll try to set up Ubuntu on a VM when I get a chance to see if I can reproduce the issue.

**Comment by psyonara** [comment]
![unicorn-dev-tools](https://user-images.githubusercontent.com/771840/104086930-90887000-5264-11eb-8c38-37071fcf4d39.gif)

I've tried it on two machines (both similar setup): so it's not anything particular to a specific computer
I've tried in Firefox: so it's not Vivaldi specific

So it could be Ubuntu...? Or just something specific that I've got running on all my computers? I'm going to try on one other computer, which has a different Ubuntu version, and doesn't have all my normal stuff on there.

Let me know if you want me to test anything. Makes more sense to have me try it, rather than you potentially wasting lots of time only to find out it's a conflict with something I have installed. :D

**Comment by psyonara** [comment]
I found the problem. It's... my password manager. :( Specifically, it's the browser plugin. When I disable it, everything works fine. So, safe to say, there's nothing wrong with Django-unicorn. :)

Sorry for the inconvenience!

**Comment by adamghill** [comment]
Ah, interesting! I wonder if it's something similar to https://github.com/adamghill/django-unicorn/issues/23 for BitWarden? Or are you using a different password manager? I probably need to figure out different ways to prevent password managers from messing with the form, but I can create a new issue for that if it makes sense.

**Comment by psyonara** [comment]
Yes, it might be a very similar cause. I use the Enpass browser extension. But no idea yet what it is doing to the form field. The source code of the extension is not exactly readable in its minified form. :(

**Comment by LeeHanYeong** [comment]
Has this not been resolved yet?
still using bitwarden the same problem :(
