### ISSUE TITLE
TemplateSyntaxError after include in exsting projects

### ISSUE THREAD

**Issue by sbidy** [adamghill/django-unicorn#125]
I get the following error if I try to integrated the framework into a existing project.
I followed the instruction in the docs and I also added the `unicorn` to INSTALLED_APPS.

**Django Version:** 3.1.1
**/usr/local/bin/python** 3.8.7 (64bit)

**TemplateSyntaxError** Invalid block tag on line 11: `unicorn_scripts`. Did you forget to register or load this tag?
/usr/local/lib/python3.8/site-packages/django/template/base.py, line 531, in invalid_block_tag

If I test the framework in a "clean" new project all work as expected. It should be something interfering with parts of the existing project. It seems that the `{% load unicorn %}` was not successful.

**Comment by adamghill** [comment]
If I remove `unicorn` from the load call in https://github.com/adamghill/django-unicorn/blob/master/example/www/templates/www/base.html#L1 I get a similar error:
![Screen Shot 2021-01-24 at 8 49 10 AM](https://user-images.githubusercontent.com/317045/105632461-3a4d2c80-5e21-11eb-88f7-583e22600764.png)

Are you sure that your template has a `load` template tag with `unicorn` in there? Is there any other helpful stacktrace in the error or anything printed to the terminal?

**Comment by sbidy** [comment]
Yes, that's the reason for the exception - the `{% load unicorn %}` was in my `base.html` was not called/excepted.
I'm not sure why because all my view templates are starting `{% extends 'base/base.html' %}`. But I've move the load statement to the my `header.html`, which is also a part of the `base.html` it works.

I'm not a django guru but must this statement after a `{% load static %}` ? I also tried it with `{% load static unicorn %}` but with no success.

**Comment by sbidy** [comment]
But If I add a "test" like the "hello world example" `{% unicorn 'hello-world' name="Universe" %}`
I get now this: `Invalid block tag on line 9: 'unicorn', expected 'endblock'. Did you forget to register or load this tag?`

The only useful from the console is:
``` bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'unicorn'
```

**Comment by sbidy** [comment]
Now, after some try and error testing I found a working "call stack":

``` html
{% extends 'base/base.html' %}
{% load static %}
{% load unicorn %}
{% unicorn_scripts %}
{% block content %}
<div class="">
    <h1>{% unicorn 'hello_world' name="Universe" %}</h1>
</div>

{% endblock %}
```

I don't now why 😆

**Comment by adamghill** [comment]
Interesting! Yes, it looks for all of my examples that use `extends` I just `{% load unicorn %}` again. I'll have to dig into Django -- from my memory I usually have to `load` templatetags in partials that get included. I'm not positive if there is a way around it, honestly.

The part that is most confusing to me is if this works
```html
{% load static %}
{% load unicorn %}
```
but this doesn't
```html
{% load static unicorn %}
```

I'll investigate some more, but thanks for the detailed bug report. I'll let you know what I discover and update the install docs to be more clear if needed.

**Comment by adamghill** [comment]
Looks like this behavior is specified as a "feature" for maintainability in https://docs.djangoproject.com/en/3.1/ref/templates/language/#custom-libraries-and-template-inheritance.

I don't know if that's how I would classify it 😆, but good to know that it works "as expected".

**Comment by sbidy** [comment]
🤣  ... ok, that's good to know.
To summarize this: I have to add the load statements in every template where add a unicorn component.

**Comment by adamghill** [comment]
Yep, TIL something new, too! :) Closing this, but let me know if you run into any other issues.
