### ISSUE TITLE
Target multiple partials

### ISSUE THREAD

**Issue by adamghill** [adamghill/django-unicorn#129]
Could be similar to class updates for dirty states (e.g. `unicorn:partial="id1 id2"`), but might be weird with `id` or `key` modifiers. Another approach might be to support multiple `unicorn:partial` attributes, e.g. `unicorn:partial="id1 id2" unicorn:partial.key="key1"`.

**Comment by ctmartinez1992** [comment]
Hey! I've been using this framework, and this would be so incredibly helpful. Any updates on this?

**Comment by adamghill** [comment]
Hi! Hopefully the framework is proving helpful. :) I think I know how the code for this feature would work, but I haven't started looking at it, yet. I'll try to get it into the next release, though.

**Comment by adamghill** [comment]
Closing because this has been merged into master and will be available in the next release.

**Comment by adamghill** [comment]
This is now available in https://github.com/adamghill/django-unicorn/releases/tag/0.27.0.

It works by supporting multiple partial attributes on an element, e.g. `<button unicorn:click="some_method" unicorn:partial.id="id1" unicorn:partial.key="key1">`.
