### ISSUE TITLE
Django can't find template of component

### ISSUE THREAD

**Issue by laxas** [adamghill/django-unicorn#159]
With my setup django can't find the template of the component where the management command put it `PROJECT/unicorn/templates/unicorn`. 

It is looking for the unicorn templates in the `PROJECT/template/unicode` folder. Works fine if I put them there. 

The templates for all other apps are found in the app specific template folders. I use the `PROJECT/template` folder only for the modified admin templates. 
``` python
INSTALLED_APPS = [
   "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    ... OTHER APPS ...  
    "django_unicorn",
]
...
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
```

**Comment by adamghill** [comment]
Do you have “unicorn” in the INSTALLED_APPS list as well?

________________________________

**Comment by laxas** [comment]
Yes, as the last element of the list.

**Comment by adamghill** [comment]
>The guide could mention it at already at the install page which might make it a bit clearer.

It's a good point. Personally, I'm a little frustrated that both are currently required, but it's a breaking change to rename the package to just `unicorn`. If I bit the bullet setup would only require the one entry in `INSTALLED_APPS` and would probably reduce some confusion. I'm still trying to figure out if I can make the change without breaking everyone's install. :)

>thanks for that great library. I am just beginning but loving it already.
Thanks! I'll close this issue now, but feel free to make an issue if you run into any other blockers or issues.
