### ISSUE TITLE
Using a unicorn view as a view

### ISSUE THREAD

**Issue by Joetib** [adamghill/django-unicorn#179]
I find myself writing duplicate views. A Django regular view that simply serves an html which does nothing but load a unicorn view and then the unicorn view itself.

I was wondering if it was possible to present the unicorn view directly to the user.

Also I was wondering if unicorn will have an equivalent of some client side routing strategy

**Comment by adamghill** [comment]
I just attached a PR with how I think rendering a component view directly might work.

Something like:

```urls.py
from example.unicorn.components.text_inputs import TextInputsView

urlpatterns = [
    path("direct-view", TextInputsView.as_view(), name="direct-view",),
]
```

How does that look to you?

I still need to figure out how the csrf token and javascript portion would get included on the page. I think that the component would extend/include a template with `{% csrf_token %}` and `{% unicorn_scripts %}`? Does that seem like a reasonable requirement?

**Comment by Joetib** [comment]
Yeah extending seems great to me.
