### ISSUE TITLE
Unicorn randomly raising checksum errors

### ISSUE THREAD

**Issue by Joetib** [adamghill/django-unicorn#184]
Well I wouldn't consider it entirely random but this happens relating to having multiple child component of the same type.
When an action is handled for one child component and then a second one, attempts to perform an action on the firs element fails.

In my particular case, it was a click event.

**Comment by adamghill** [comment]
Can you give me some example code? I have multiple child row components in my nested example: https://github.com/adamghill/django-unicorn/blob/master/example/unicorn/templates/unicorn/nested/table.html#L31. The table component also might be useful to see what I ended up doing to make it all work correctly: https://github.com/adamghill/django-unicorn/blob/master/example/unicorn/components/nested/table.py.

**Comment by adamghill** [comment]
Any update on whether this is still happening or any example code I can take a look at to investigate?

**Comment by adamghill** [comment]
I'm going to close this for now, but feel free to re-open it if you have some sample code I can look at. Thanks!
