### ISSUE TITLE
Many To Many Relation Issues based on the relation direction

### ISSUE THREAD

**Issue by mbacicc** [adamghill/django-unicorn#186]
Dear Adam,
I've seen on your latest commits that this part of code is of recent development and maybe you're still working on it.
I was trying it on my model and I was not having the desired results such the one in the Model Example.
Looking at the code and with some debug I think I found the issue. The M2M relation is bi-directional, but is declared on just one of the two models, and they don't share the same field meta parameters. Let's talk about the coffee model, while you traverse the M2M in opposite direction, as in the example, you must work on the related_name field, which is not there if you try to traverse the same relation starting from the model Flavor. To understand on which side of the relation you are I managed to use the auto_created attribute, based on that you can use related name or name.
I attach you the diff file.
Have a try and thank you for your amazing work!

[8ded32dbaa5cadd4ccfefe1dfae531fe73003529.diff.txt](https://github.com/adamghill/django-unicorn/files/6355737/8ded32dbaa5cadd4ccfefe1dfae531fe73003529.diff.txt)

**Comment by adamghill** [comment]
Of course! I totally forgot about the other side of the many-to-many. This diff is very useful, do you want to send me a PR so you get credited with the code change? Updating the tests to check the other side of the relationship would also be great if possible!

**Comment by mbacicc** [comment]
Actually I'm not super expert with Github flow and I don't want to screw things up.
I also never used tests, sorry :(

**Comment by adamghill** [comment]
@all-contributors add @mbacicc for code

**Comment by adamghill** [comment]
Ok, no worries! Based on your diff I was able to add the fix and tried to credit you for the code as much as possible. I'm going to bump the version a minor and release it now to include this fix. Thanks for your help finding that bug! 🎉
