### ISSUE TITLE
Add the possibility to add a timeout function to self refresh the view

### ISSUE THREAD

**Issue by mbacicc** [adamghill/django-unicorn#187]
Would be nice to have the possibility to set from the python component a timeout to be passed to js to do an AJAX call and refresh the fields.

**Comment by adamghill** [comment]
Would this be just a single refresh, not continuous like a poll? You might be able to hack something together with a disabled poll and using https://www.django-unicorn.com/docs/polling/#pollupdate, but it probably wouldn't be pretty.

Can you tell me more about the use-case where this would be useful?

**Comment by mbacicc** [comment]
Sorry about that, skipped that part of the documentation.
I was thinking about small items inside page which poll for updated info, notifications, messages and so on, but it was already there.
My bad.
