### ISSUE TITLE
Issue with ForeignKey in a Model

### ISSUE THREAD

**Issue by mbacicc** [adamghill/django-unicorn#189]
I actually found the same issue (on master tree I could not find this commits) with one of my models.
The solution that I managed to implement was actually just to comment the row:
`set_property_from_data(field, field.name, value)`
and replace it with:
`setattr(component_or_field, name, field)`
in `django_unicorn/views/utils.py`

After finding this solution, I found this PR and I tried this code, which was causing error on my page.

What I actually have is a model with a foreignkey to User. When user is empty @Joetib version fails, while the standard 0.27.0 version works. When user was set, original was not working, didn't try this PR in that case. My version seems to work in both cases, but I'm not sure if I may have broken other parts of the code, since I didn't fully understood how it works.

_Originally posted by @mbacicc in https://github.com/adamghill/django-unicorn/issues/178#issuecomment-824907169_

**Comment by adamghill** [comment]
@mbacicc Can you check 0.27.1 and see if it works for your use-case? Thank you!

**Comment by mbacicc** [comment]
Hi Adam,
I tried 0.27.1. I see that it solves #186 in a more elegant way than my solution :)
Unfortunately, it still doesn't work with this issue.
Let me explain my test case in a simpliefied version (I removed some unuseful fields for readability)
I have a Board model which identifies electronic boards.
Then I have a unicorn component which shows and allows editing of the Board Model. I used a code very similar to nested/table.py example from your repo.
[simple_model.txt](https://github.com/adamghill/django-unicorn/files/6363689/simple_model.txt)
[component.txt](https://github.com/adamghill/django-unicorn/files/6363692/component.txt)
[component_template.txt](https://github.com/adamghill/django-unicorn/files/6363699/component_template.txt)
Unfortunately with this 0.27.1 version I get no debug messages, but when I press the edit button from the template, the edit code in my component is never triggered. The request gets error 500: 
AttributeError at /unicorn/message/djara-hw-board-details-info
'User' object has no attribute 'name'
This error continues happening as long as the Foreign keys of Board model are linked. If I remove all the links, like this:
![image](https://user-images.githubusercontent.com/46646960/115840643-3038cb00-a41c-11eb-86e4-ae8640851c06.png)
It starts working properly, but if I create a connection, even with my component, I'm able to create it, but next time stops working  returning error 500. This also happens if the M2M relation in Board is linked.

My fix for this is on row 62 of django_unicorn/views/utils.py ,like I suggested in previous comment.
If I apply this fix to 0.27.1 it starts working properly (at least in this use case). It solves this issue, but I don't know if it is a safe solution in all other cases.

Thank you for your efforts. I really like this component. It's really useful.

**Comment by mbacicc** [comment]
I can try to submit a PR for the first time with this fix just to see how it works. Would it be ok for you?

**Comment by mbacicc** [comment]
I submitted PR #191 .
Hope I didn't do anything wrong.

**Comment by adamghill** [comment]
More details are in #191, but I think this is fixed in 4a3d4c769a0a, so I'm going to close this issue. This is now released to PyPI in version 0.27.2.
