### ISSUE TITLE
Any examples with skeleton loaders?

### ISSUE THREAD

**Issue by brno32** [adamghill/django-unicorn#195]
I'm a Django and React dev doing whatever I can to drop React.

One thing that lures me to React is the ease with which you can customize behavior around asynchronous data fetching. This library looks cool. Are there any plans to customize the loading state in the template? Or any examples of how one could already do that?

**Comment by adamghill** [comment]
Is https://www.django-unicorn.com/docs/loading-states/ what you mean or can you point me to a specific blog post/documentation/example? Thanks!

**Comment by brno32** [comment]
That example answers my question. Thanks!

**Comment by adamghill** [comment]
Awesome! I'll close this now, but create a new issue if the loading states don't work as expected, or you need other functionality.
