### ISSUE TITLE
Investigate pysimdjson instead of orjson

### ISSUE THREAD

**Issue by adamghill** [adamghill/django-unicorn#20]
https://github.com/TkTech/pysimdjson

**Comment by zodman** [comment]
do you consider simplejson ?

**Comment by adamghill** [comment]
My main reason for choosing orjson originally was for speed reasons (https://github.com/ijl/orjson#performance) and easily supporting more types (https://github.com/ijl/orjson#serialize) than the built-in `json` or `simplejson`. `pysimdjson` might be even faster, but it probably doesn't matter for the small bits of JSON that is serialized/deserialized here, though. Probably fine to just stick with what works unless it seems to be a bottleneck.

**Comment by adamghill** [comment]
Closing this at least for now. I don't see a lot of reason to use a different JSON encoder currently.
