### ISSUE TITLE
select option html not working

### ISSUE THREAD

**Issue by paolinux-61** [adamghill/django-unicorn#204]
congratulations for this package django we lacked a solution so to make the life of us developers easier. Kindly if you have much more substantial examples and where to find them that I am developing a django solution and would like to use this package to rewrite it much more interactive. Thank you keep it up.

but we come to us I am trying to use select option html but without succeeding in full.

i read over internet for functioning this example code of django in component template write this:

```
<select name="valore" id="cambio_cod" onchange="Unicorn.call('ricerca', 'cambio_cod' );">
      <option value '' selected>-- Seleziona --</option>
      {% if utenti %}
      {% for kappa in utenti %}
      
      <option value '{{kappa.dipendmatric}}'>{{kappa.dipendcognom}} {{kappa.dipendnome}}</option>

      {% endfor %}

      {% else %}
        
      {% endif %}
    </select>

```

but not working - populate well but if i click on option value not return nothing ???

**Comment by adamghill** [comment]
The way I would normally do this is use `unicorn:model` in the select element to bind it to a field in the component view. Like this: https://github.com/adamghill/django-unicorn/blob/master/example/unicorn/templates/unicorn/html-inputs.html#L22-L26 and https://github.com/adamghill/django-unicorn/blob/master/example/unicorn/components/html_inputs.py#L7.

Let me know if that doesn't work for you!

**Comment by paolinux-61** [comment]
Tanks a lot now functioning :)
i want not utilizing button and in this manner when click on element execute method in component search and return 
the value to template 




```
{% if utenti %}
<select unicorn:model="trovautente" id="trovautente" class="form-control form-control-sm" onchange="Unicorn.call('ricerca', 'selezutenti' );">
  <option value '' selected>-- Seleziona --</option>
  {% for kappa in utenti %}
  <option value='{{kappa.id}}'>{{kappa.dipendcognom}} {{kappa.dipendnome}} {{kappa.ufficicsmdescri}}</option>
  {% endfor %} 
</select>
{% endif %}
```
```

class RicercaView(UnicornView):

trovautente = ""


    def selezutenti(self):
      
      
        print(self.trovautente)
        if self.trovautente  == "": 
            q3a = ""
        else:
            q3a = utentecsm.objects.get(id=self.trovautente)        
            self.nomeutente = q3a
            self.utenti = ""
            return self.nomeutente, self.utenti


```

please you can resolve me another my problem?  I want create component for zoom canvas image - i realized this with javascript and functioning well but in unicorn not found the manner of trigger dblclick event - 
ondblclick="Unicorn.call('zoom', 'ingrandisci' ); not functioning ??? Thanks  :)

**Comment by adamghill** [comment]
The `ondblclick` event should work as expected. Can you show me more code of what you are trying to do or fork the example project in this repo with an example? Thanks!

**Comment by adamghill** [comment]
I'm going to close this issue since it's been more than a month, but feel free to open it with example code that I can use to replicate. Thanks!
