### ISSUE TITLE
Typo in model docs - delete instead of save call

### ISSUE THREAD

**Issue by GitRon** [adamghill/django-unicorn#205]
Hi there! 

I think I maybe have found a tiny bug in the docs. Have a look at the following page:

https://www.django-unicorn.com/docs/django-models/

In the models.py exaple lives this code:

```
def save(self, book_to_save: Book):
        book_to_save.delete()
```

I guess that should be "save" instead of "delete"?

I tried to fix it myself but unfortuately couldn't find the docs in the repo.

Best regards 
Ronny

PS: Nice talk yesterday at the djangoCon Europe!

**Comment by adamghill** [comment]
Thanks for the catch! I am just pushing the documentation site out with this fix: https://github.com/adamghill/django-unicorn.com/commit/a71598840617c32f93689cbf56ffd1d2160c364e.

**Comment by adamghill** [comment]
@all-contributors please add @GitRon for doc

**Comment by adamghill** [comment]
Thanks again! Please create a new issue if you find any other problems. :)

**Comment by GitRon** [comment]
Super fast! Thx 😄
