### ISSUE TITLE
Documentation section covered

### ISSUE THREAD

**Issue by fabiancook** [adamghill/django-unicorn#207]
![image](https://user-images.githubusercontent.com/4337080/120877235-88f9a700-c609-11eb-936b-0efa79cf664e.png)
![image](https://user-images.githubusercontent.com/4337080/120877341-1dfca000-c60a-11eb-886b-904e9c2ff169.png)
![image](https://user-images.githubusercontent.com/4337080/120877345-21902700-c60a-11eb-94a6-416c0d1b0b17.png)
![image](https://user-images.githubusercontent.com/4337080/120877352-2bb22580-c60a-11eb-8530-2f4843ec1944.png)

I also noticed another rouge looking one here:

![image](https://user-images.githubusercontent.com/4337080/120877362-38367e00-c60a-11eb-93bd-126e3de28c3a.png)

**Comment by adamghill** [comment]
Huh, that's weird! Can you tell me what OS, browser, screen-size you are using? Those are being done by https://roughnotation.com/, I wonder if the annotations on their homepage are also placed in the wrong spot?

**Comment by fabiancook** [comment]
macOS, Chrome 90.0.4430.212,  1920 x 1080

**Comment by adamghill** [comment]
I never could replicate this on my computers so closing this for now. If it's still an issue, I'm guessing it's related to https://roughnotation.com/ and there isn't much I can do on my side.
