### ISSUE TITLE
Looks promising

### ISSUE THREAD

**Issue by heyaustinwood** [adamghill/django-unicorn#22]
How can I help? I’m a web designer/developer (HTML + CSS) and haven’t taken the leap into the front-end frameworks.

I like the idea of components but all of the overhead in the front-end frameworks is overwhelmingly complex and changes far too often to keep up with a small team.

We have a couple of projects which use Django with templates.

This project looks like something we would be interested in. 

How can we help?

**Comment by adamghill** [comment]
Howdy @heyaustinwood! The project is still in its infancy, but it should work for really simple cases. The best thing to do would probably be to try it out for some places on your site and see how it works. Are there places where you get stuck in the documentation? Do things not work as expected? Is there something you are trying to do that doesn't seem possible? That would be super helpful, thanks!

**Comment by heyaustinwood** [comment]
Everything looks clear so far. Thanks for putting in the work up to this point. We will work to find a place to implement it into our project in the next month or so. Stay tuned.

**Comment by adamghill** [comment]
Rad! 👍 Closing this for now, but feel free to open another issue if you run into any problems.
