### ISSUE TITLE
startunicorn uses wrong app path for component creation

### ISSUE THREAD

**Issue by nerdoc** [adamghill/django-unicorn#228]
When creating a new component using the startunicorn cmd, you get asked `Use '...' for the app directory? [Y/n]`.

In my cast the app directory of the "cashbook" app is `/home/christian/Projekte/medux/medux/plugins/cashbook`. Unicorn seems to blindly assume that the directory is BASE_DIR  / <appname> - which is not true - it suggests `/home/christian/Projekte/medux/cashbook`.

It should use the app's real path.
Here's the cuplrit:
https://github.com/adamghill/django-unicorn/blob/e512b8f64f5c276a78127db9a05d9d5c042232d5/django_unicorn/management/commands/startunicorn.py#L57

**Comment by nerdoc** [comment]
I wrote a PR wo fix this. But I don't want to change other things that are affected there: ATM you are asking to create that app directory if it does not exist. I think this is not a good idea as it duplicates Django's startapp functionality - which may change over time - maybe the models.py gets some defaults etc. - honestly, you only create the app dir.
If you want this as the desired behaviour, I'll modify my patch to respect that.
But if you can live with a CommandError that is raised when the given app path is not found with the hint that you have to create that app first using `startapp`, let me know, then I'll publish this PR...

I think that it even could lead to problems, when you have a typo in the app name:

    ./manage.py unicorn cashbok foo_component

 when the real app  name is `cashbook`. So you end up with a wrong app name and have to delete it again (maybe side case).

Please tell me what you think.

**Comment by adamghill** [comment]
https://github.com/adamghill/django-unicorn/pull/229/files#diff-e430055856332e85d9413645d761cba7979aaa747b55ec8dcecfd9d6f00b2c70R59 is a great addition -- I didn't realize that API was available and is definitely less error prone than the original code. Thanks for that.

My original intention for `startunicorn` was to either 1) add a component view and template to an existing app, or 2) create a folder with the least amount needed for a component. My understanding is Django apps don't actually require anything specific anymore (maybe an `apps.py` is needed, though now that I think about it?). However, if the `app_name` is missing, it _could_ call `startapp` programmatically (https://github.com/django/django/blob/ca9872905559026af82000e46cde6f7dedc897b6/django/core/management/commands/startapp.py) after an initial `input` question to find out if that was the intention?

The hope is to find a nice balance and have the command "just work" as expected. Maybe exiting out and telling the user to run another command is the right approach, but it seems like I know what the user was trying to do, so maybe I should just do it for them. But, open to the idea that it's unexpected to a folder to be created at all, too.

**Comment by nerdoc** [comment]
I am a big friend of smooth workflows, definitely. But, I also like the Unix principle: "do one task, and do it well". During development of my GDAPS plugins system for Django, I often came to a point where I completely reduced the behavior again, just to make it less complex and intransparent.
While I think the unicorn cmd should make it as easy as posible, I also am sure that mostly you will **not** create a new app for every unicorn component, but have a few apps, with each having a few components.
So, the benefit of "creating" an app on the fly in the background when creating a unicorn component is "most of the time" **not** what a user wants IMHO.
And Django does this part very well, I wouldn't reinvent the wheel here again.

There could be cases when you want  an app with the absolute minimum possible, without models etc. But really, if you have such a minimalist application, it's not a problem to just do a `./manage.py startapp foo` and delete what's too much, and then create 3 components using `./manage.py startunicorn foo component1 component2 component3`.

But I really like the straightforward and pythonic way Unicorn works in general, my warmest compliments here.

**Comment by nerdoc** [comment]
>  However, if the `app_name` is missing, it _could_ call `startapp` programmatically (https://github.com/django/django/blob/ca9872905559026af82000e46cde6f7dedc897b6/django/core/management/commands/startapp.py) after an initial `input` question to find out if that was the intention?

Regarding that - exactly where I was with GDAPS - I reinvented the whole template system of Django again... because it lacked some features. Then I wanted to do the internal call of a mgmt cmd...  Until a few days ago, where I threw it out of the window and took cookiecutter. Much better now. (https://gitlab.com/nerdocs/gdaps-plugin-cookiecutter)

**Comment by adamghill** [comment]
Gotcha. I agree that almost all of the time, the app wil still be there, so handling the new app use case feels like additional complexity for not a lot of win, but it still feels like the right thing to do and it's what I would want as a user. So, I'd like to ask if the user wants it created via `startapp` and run the management command if they reply "yes". If the user replies "no", then exit out and let them handle it themself.

Let me know if you want to add that to your existing PR, otherwise I'll add it in the next day or so!

**Comment by nerdoc** [comment]
That would be a nice idea. if the app does not exist, ask for it and call startapp.
I don't have time at the moment for implementing - feel free, thanks!

**Comment by adamghill** [comment]
Done in https://github.com/adamghill/django-unicorn/pull/242 and merged into master.
