### ISSUE TITLE
move css/js files into static/unicorn/ folder

### ISSUE THREAD

**Issue by nerdoc** [adamghill/django-unicorn#239]
I recently discovered as I deployed a project using Unicorn that `manage.py collectstatic` puts the static files of Unicorn into global `css` and `js` folder within `static/` (meaning the configured static files directory of Django).
Django itself (e.g. the admin app) uses a structure similar to the recommended templates examples in the tutorial: use the app name as namespace.
Unicorn e.g. has a few `svg/oval.svg[.gz] ` files which get copied into `static/svg/oval.svg`.
Same with js files. If any app uses another "utils.js" file, I suppose Django gets a problem...  

This could be easily solved by putting files into an 'unicorn/` namespace folder within `static/`

This would make bigger installations easier. What do you say about that, @adamghill ?

**Comment by adamghill** [comment]
Yep, this is definitely an oversight on my part and should be relatively straight-forward to fix. I think using `unicorn/static/django_unicorn/` instead of just `unicorn/static/` would be work well. Will add this to the next release.

**Comment by adamghill** [comment]
Closing because this has been pushed into master and will get deployed in the next release.

**Comment by nerdoc** [comment]
Sorry to ask again, but why unicorn/static/django_unicorn/? and not unicorn/static/unicorn/?

**Comment by adamghill** [comment]
Could be either, my thought was potentially someone would have an app named `unicorn` (like, for example I do in my example app) whereas `django_unicorn` is much less likely to conflict with anything else.

That being said, the chance of other unicorn apps out there is pretty slim, so I'm open to that as well if you think it makes more sense.

**Comment by nerdoc** [comment]
Ah, OK. But if so. uses Unicorn AND names his own app 'unicorn', that:s either intended to use the same namespace, or by mistake IMHO. Unicorn  by definition uses that namespace :) In your case, couldn't it be a possible solution to name *your* app <something>_unicorn?

**Comment by adamghill** [comment]
Makes sense and works for me. I'll update it to be `unicorn`. 👍
