### ISSUE TITLE
Updated_search function not being called (filter table)

### ISSUE THREAD

**Issue by Franziskhan** [adamghill/django-unicorn#249]
Hello Adam (@adamghill ),

first of all sorry for bombing you with lot of requests, but unfortunately I'm getting a problem while using the search filter function of Django Unicorn.

I am creating for my company an app that manages transport documents (DDT), and i made  a table where all documents are shown. The problem is filtering them with search and other filters (like "show only 2021 documents").
I cannot show whole project or make a pull requests of course, so i'll show just the template that call components, table component and filter component. If something is missing in this post it means that i'm missing something in my project too.

The filter component is nearly copied from the _nested table_ in your example, it's all the same or correctly adapted, so i'm not getting why it's not working on my project.
The _updated_search_ function is not even called when the search field is updated, for some reason.

ddt_out_list.html
```
{% extends 'logistics/base.html' %}
{% load static unicorn %}

{% block content %}
{% unicorn 'ddt-table' %}
{% endblock content %}
```

ddt-table.html

```
{% load unicorn static %}

<div>
    {% unicorn 'filter' parent=view %}
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Short Description</th>
        <th>Creation Date</th>
        <th>Status</th>
        <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for ddt in ddts %}
            <tr>
                <td>{{ ddt.id }}</td>
                <td>{{ ddt.ldo_name }}</td>
                <td>{{ ddt.ldo_short_description }}</td>
                <td>{{ ddt.ldo_creation_date }}</td>
                <td>{{ ddt.ldo_status }}</td>
                <td>(Add edit button)</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
```

ddt_table.py

```
from django_unicorn.components import UnicornView
from logistics.models import *

class DdtTableView(UnicornView):
    ddts = Logistics_DDT_Out_List.objects.none()

    def mount(self):
        self.load_table()
       
    def load_table(self):
        self.ddts = Logistics_DDT_Out_List.objects.all()
```

filter.html

```
<div>
    Filter: <input type="text" unicorn:model="search" /><br />
    Search: "{{ search }}"
</div>
```

filter.py

```
from django_unicorn.components import UnicornView
from logistics.models import *


class FilterView(UnicornView):
    search = ""

    def updated_search(self, query): #this function is not called when the search field is updated. Why?
        self.parent.load_table()

        if query:
            self.parent.ddts = list(
                filter(lambda f: query.lower() in f.ldo_name.lower(), self.parent.ddts)
            )
```

Thanks for all support.

**Comment by adamghill** [comment]
I used your code for https://github.com/adamghill/django-unicorn/commit/5c851afa5533dfff2374a9ab2030542b3457da5c, but swapped out the model and it typing in the search box _seems_ to work for me.

I get `updated search?` in the console output:
![Screen Shot 2021-07-27 at 9 28 51 PM](https://user-images.githubusercontent.com/317045/127249038-c09edadd-a700-4021-9a45-8a7e717fa0e5.png)

Example in a browser:
![issue-249](https://user-images.githubusercontent.com/317045/127249213-1199ec31-68b9-4c22-8c09-2cfdb666c89b.gif)

Do you get any browser console or web server errors?

**Comment by Franziskhan** [comment]
I did as you suggested, first it asked me to load _unicorn_scripts_, despite I'm not getting why (in your example they are loaded only in _base_):
`(index):387 Unicorn is missing. Do you need {% load unicorn %} or {% unicorn_scripts %}?`

I loaded unicorn_scripts, and then  something happened.
Now it gets when the field is edited, well it gives two error messages, and generic ones, but at least the error messages appear as I type something in the field:


`POST http://localhost:8000/unicorn/message/filter 500 (Internal Server Error)`

`Error: Error when getting response: Internal Server Error (500)`

**Comment by Franziskhan** [comment]
However, since my code works in your repository, I'm thinking that is not something regarding the code itself but something in the corner... I don't know if I'm missing something somewhere...

**Comment by adamghill** [comment]
Re: https://github.com/adamghill/django-unicorn/issues/249#issuecomment-888199890:

Can you look at the output from the Python shell? The error should be there and might give you a clue!

**Comment by Franziskhan** [comment]
Hello again Adam,

sorry for late answer, due to vacation.
Seems something changed with the new releases of Unicorn?
The python shell is not flagging any error. Actually, now the filter function is called, well, it only change the filter word as I type something on keyboard, but it's not actually filtering my table. Anyway I'll let you know if I will fix it, otherwise i'll let you know.

Thanks for all and see you!

**Comment by adamghill** [comment]
👍 No worries! I'm going to close this issue for now, but feel free to re-open it if you need to later.
