### ISSUE TITLE
Use rindex when handling installed app that points to an app config

### ISSUE THREAD

**Issue by apoorvaeternity** [adamghill/django-unicorn#267]
@adamghill - This is a very nice project. Kudos.

I faced a very small issue while trying to use `django-unicorn`. It also has to do with our own directory structure. We have a bunch of apps inside another `apps` directory.
 
The issue is that our app config is inside `proj.apps.core.apps.CoreConfig`. `django-unicorn` tries to find the component inside `proj.components` instead of `proj.apps.core.components`. I think if  in the code below`app.rindex(".apps.")` is used instead of `app.index(".apps.")` that would fix the issue for us(and prevent a big rewrite of the codebase or the burden of maintaining a fork).
 Also, looking at the code I think the actual intention is to find the right most index of `.apps.`.

```
for app in unicorn_apps:
        # Handle an installed app that actually points to an app config
        if ".apps." in app:
            app_config_idx = app.index(".apps.")
            app = app[:app_config_idx]

        app_module_name = f"{app}.components.{module_name}"
        locations.append((class_name, app_module_name))
```

I would be happy to create a PR for this.

**Comment by adamghill** [comment]
Yep, `rindex` seems like a better approach. I'd love a PR with a test. 👍
