### ISSUE TITLE
cannot start component 🤔

### ISSUE THREAD

**Issue by lolrenx** [adamghill/django-unicorn#274]
Hello, 

I'm super pumped about your work and looking forward to using it, but I can't create a component following the installation screencast. 

the server runs correctly. 

I've rebooted, reinstalled the dependencies, changed from pipenv to poetry to venv, tried in iterm, vscode, terminal. 🤷 

environment : macOS 12.0 Beta (21A5506j) M1 mac

```
python manage.py startunicorn sightings
usage: manage.py startunicorn [-h] [--version] [-v {0,1,2,3}]
                              [--settings SETTINGS] [--pythonpath PYTHONPATH]
                              [--traceback] [--no-color] [--force-color]
                              [--skip-checks]
                              app_name component_names [component_names ...]
manage.py startunicorn: error: the following arguments are required: component_names
```

settings : 

```
INSTALLED_APPS = [
    "django_unicorn",
    ...
]
```

urls : 

```
urlpatterns = [
    path("unicorn/", include("django_unicorn.urls")),  # Django Unicorn url integration
    ...
]

```

thanks !

**Comment by adamghill** [comment]
Oh no! I need to re-record that screencast. Can you try following this? https://www.django-unicorn.com/docs/components/#create-a-component I added a required argument to the `startunicorn` command.

You could try `python manage.py startunicorn unicorn sightings` to create a new `unicorn` application. Or specify a different application name if you want. Hopefully that works! Let me know. 👍

**Comment by lolrenx** [comment]
Oh well. Looks like I should have RTFM ! 

Thanks Adam, I can push on with my search of legendary one-horned equidae ! 

peace !

**Comment by lolrenx** [comment]
BTW the CLI documentation is also showing the old syntax :) 

https://www.django-unicorn.com/docs/cli/

**Comment by adamghill** [comment]
Oh, shoot. Thanks for letting me know, I'm pushing a fix for that page right now. 👍
