### ISSUE TITLE
Allow sub directories for components

### ISSUE THREAD

**Issue by riquedev** [adamghill/django-unicorn#299]
Wouldn't it be interesting to enable the creation of subfolders inside components?
It is currently possible as long as we create the folders in advance.
```
The "event" folder was previously created

...> python manage.py  startunicorn "ABXSite" event\schedule
Created ...\components\event\schedule.py.
Created ...\templates\unicorn\event\schedule.html.
```

However, you cannot use components in subdirectories, perhaps a schema like:

{% unicorn "folder:component" %}

As in {% url "appname:view" %}

**Comment by adamghill** [comment]
Nested components are supported. You can see an example in https://github.com/adamghill/django-unicorn/tree/master/example/unicorn/components/nested and https://github.com/adamghill/django-unicorn/tree/master/example/unicorn/templates/unicorn/nested. You use a `.` (like Python namespaces) to access components in sub-folders. An example of that is: https://github.com/adamghill/django-unicorn/blob/a54cdaf933b7541601029aaa84e823af595e5c26/example/unicorn/templates/unicorn/nested/table.html#L19.

However, I'm not sure if the `startunicorn` supports creating folders for nested components, but that seems relatively easy to add in if it would be useful. And I can add some documentation around this capability as well!

**Comment by adamghill** [comment]
This has been merged into master and will be released in the next version.
