### ISSUE TITLE
Values passed by template context_preprocessors are not available in component template

### ISSUE THREAD

**Issue by apoorvaeternity** [adamghill/django-unicorn#300]
Hey @adamghill - it looks like the values passed by `context_preproccesors` are not available in the component template.
for eg. I can't get the value of `debug` passed by `django.template.context_processors.debug` in the component template.

```
TEMPLATES = [
    {
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
            ],
            .
        },
        .
    },
]
```

**Comment by adamghill** [comment]
Interesting! Let me check into what might be going on and get back to you. 👍

**Comment by adamghill** [comment]
This should now work in 0.38.0. Let me know if it doesn't work for you!

**Comment by apoorvaeternity** [comment]
Thanks @adamghill 🙂
