### ISSUE TITLE
ValueError: Field 'id' expected a number but got ''.

### ISSUE THREAD

**Issue by SelmiAbderrahim** [adamghill/django-unicorn#321]
Everything is working, but at some points, I got some errors and they disappear once I refresh the page.
For example, this component is used to up-vote a reply, a user can't use this feature unless he reloads the page.

Template:
`{% unicorn 'upvote-reply' reply_id=reply.id user_id=request.user.id %}`

views:
```
...
class ReplyUpvoteView(UnicornView):
    reply_id = ""
    user_id = ""
...
```

And thanks for your amazing project, it's very helpful to create dynamic websites.

**Comment by SelmiAbderrahim** [comment]
Okay, my mistake was not dpecifying **Property type**.
the reply_id has to be an integer, but I declared as **str**.
So I fixed by 

...
class ReplyUpvoteView(UnicornView):
    reply_id: int = 0
    user_id: int = 0
...

**Comment by adamghill** [comment]
Glad you got this working! The field types help `Unicorn` be a little smarter, so your fix makes sense. Let me know if you run into any other issues. 👍
