### ISSUE TITLE
Direct View ignores extra_context after update

### ISSUE THREAD

**Issue by nerdoc** [adamghill/django-unicorn#328]
Hm. I tried the new "Direct View" - which is a *great* feature IMHO, but I have some problems with it.
I have a view:
```python
class PrescriptionApproveListView(PermissionRequiredMixin, UnicornView):
    """List view for prescription request approvals"""

    permission_required = "prescriptions.approve_request"
    object_list = PrescriptionRequest.objects.all()
    template_name = "unicorn/prescriptionrequest_list.html"
    extra_context = {"approval": True}
    ...
    def approve(self, id):
        object = PrescriptionRequest.objects.get(pk=id)
        object.approved = True
        object.save()
        print("appoved:", id)
        self.object_list = PrescriptionRequest.objects.all()
```
And a template which does some rendering, and checks if `approval` is `True`, which it uses for conditional rendering.
There is another Direct View which uses the same template, and doesn't have the "approval" variable.

I now see that the template works, and if I click the "approve" button (which should call `approve()`), does somehow not call the method, (don't know why), but worse: the template looses the "extra_context" attribute and is rendered without it.

I even removed the extra_context attr, and just gave it a `approval = true` as Component attribute. Nope.

I'm stuck now. any hints? If you want I can give you the template as well, but it's a bit complicated. Basically, it's this (simplified):

```html
  <table class="table">
    <thead>    <tr> <th ...</th>... </tr>    </thead>
    <tbody unicorn:view>
    {% csrf_token %}
    {% for object in object_list %}
    <tr>
        <td>
        ...
        {% if object.approved %}
              ...
        {% else %}
              ...
        {% endif %}
        </td>
        ...
    </tr>
    {% endfor %}
    </tbody>
  </table>
    ...
```

**Comment by nerdoc** [comment]
Maybe I have the problems because I cave 2 component classes (using the same template) in one `components/prescriptionrequest_list.py` file. Is this valid? Or does a component require to have just one class per file?
Because I get other problems as well there :-(

**Comment by adamghill** [comment]
Sorry you are running into this issue! I assume this component was used before inside a regular template and everything worked as expected?

If you could fork https://github.com/adamghill/django-unicorn/blob/master/example/unicorn/components/direct_view.py and replicate this issue with the smallest amount of code that would be awesome. 👍  Otherwise, I'll try to replicate as soon as possible.

>Maybe I have the problems because I cave 2 component classes (using the same template) in one components/prescriptionrequest_list.py file. Is this valid?

Whoa, I've never tried it! I'd expect it to work if you directly call the component from the template, e.g. `{% unicorn 'unicorn.components.presecriptionrequest_list.FirstComponent' %}`. I'll have to check into this, too. :)

**Comment by nerdoc** [comment]
Sorry. I managed it, was a dumb error, nothing to do with Unicorn. I'll close this for now. If I have a problem with the 2-in-1 views, I'll open another issue.

**Comment by adamghill** [comment]
Ok! Good to know. Thanks for closing. 👍
