### ISSUE TITLE
Apache Timeout

### ISSUE THREAD

**Issue by xinspl** [adamghill/django-unicorn#339]
When 'django-unicorn' is in INSTALLED_APPS the apache2 server on ubuntu20.4 timeouts. Logs shows:
-Timeout when reading response headers from daemon process
-Truncated or oversized response headers received from daemon process 

googling it I find fix in stackoweflow [https://stackoverflow.com/questions/40413171/django-webfaction-timeout-when-reading-response-headers-from-daemon-process](url)

I inserted to apache2.conf :
`WSGIApplicationGroup %{GLOBAL}`

but i wonder why is that even happening? Any hints on how to track the issue? 

PS. Adam this is awsome package !!!

**Comment by adamghill** [comment]
Do you get the same errors when `Unicorn` is not included in `INSTALLED_APPS`? It looks like that fix mentions `numpy` and `scipy`. `Unicorn` doesn't use either of those libraries, but maybe the `orjson` dependency is causing an issue? It's rust and not C, but it's the only thing I can think of that is sort of "non-standard" and not pure Python as far as I know.

I'm glad that fix worked for you. I've never seen that issue crop up before, but if I can replicate it I'll re-open this issue in the future.
