### ISSUE TITLE
Message response is not considered on 304 Not Modified

### ISSUE THREAD

**Issue by jeromelebleu** [adamghill/django-unicorn#365]
To simplify this issue, we could consider a component with on method which returns state A, then B, then A. On the last call, the server returns a 304 Not Modified response. As a consequence, `response.ok` is false [here](https://github.com/adamghill/django-unicorn/blob/0.42.1/django_unicorn/static/unicorn/js/messageSender.js#L49) and the dom is not updated.

I don't have a good understanding yet of this nice project - thanks by the way - but I would be happy to help as needed. Feel free to ask more details as needed.

**Comment by adamghill** [comment]
@jeromelebleu Thanks for the report. `Unicorn` returns a 304 at https://github.com/adamghill/django-unicorn/blob/main/django_unicorn/views/__init__.py#L232 (tested in https://github.com/adamghill/django-unicorn/blob/main/tests/views/message/test_hash.py#L9-L33) if it doesn't look like the data has been updated.

If you can replicate an issue with this functionality with a PR or test I'd love to see it.

**Comment by jeromelebleu** [comment]
Thanks for you answer and this pointer, it helps me to realize that it was a bug from my side, my apologies…

**Comment by adamghill** [comment]
No worries! Let me know if you run into any other issues. 👍
