### ISSUE TITLE
Error message misleading when  component class or .py file is mis-named

### ISSUE THREAD

**Issue by nerdoc** [adamghill/django-unicorn#373]
If you mis-name a component, e.g. `BlockeditView` instead of `BlockEditView` (leave the python file name as it is...), you get a weird error message:

    'block_edit' component could not be loaded: No module named 'medux_online.plugins.prescriptions.components.block_edit'

Which is quite nonsense.
1. The message should not just print out the `last_exception`: This is just the last directory where Unicorn was searching in. It's misleading, in my case I don't have even a `compnents` directory in `medux_online.plugins.prescriptions`, the component is in `medux_online.plugins.homepage`. So the error message just leads to a search in the wrong place for the error... 
2. It should instead tell you the name of the component class which was not found. It is a difference if the python file name is spelled wrong, or if the class name is written incorrectly. Unicorn should reflect that and give a proper error message, like:

ad 1) Python file spelled wrong/not there (import fails):

    The component "block_edit" was requested, but no app contains a "components/block_name.py" file.

ad 2) the class name is spelled wrong (class not found):

    The component class "BlockEditView" was not found in any app.

... or similar

**Comment by nerdoc** [comment]
A possible solution would be, to rename `last_exception` to `error_message`, let it be a str, and git it a meaningful content. So nothing else must be changed. E.g. something like

```python
last_exception = f"The module '{module_name.split('.')[-1]}' was not found in any app's 'components' package."
```

**Comment by adamghill** [comment]
Yeah, the errors aren't super useful I agree. https://github.com/adamghill/django-unicorn/pull/374 has a PR that I think improves the error messages, let me know how it looks.

**Comment by adamghill** [comment]
Closing this issue since the PR has been merged into `main` and will go live in the next release.
