### ISSUE TITLE
How to call "Unicorn.call()" to a component with a specific key?

### ISSUE THREAD

**Issue by jacopsd** [adamghill/django-unicorn#383]
The help pages show this example to call a component from js:

```
<button onclick="Unicorn.call('hello-world', 'set_name');">
  Set the name from outside the component
</button>

```
But if 2 instances of this component exist on the same page, how can a specific component (identify by a key) be called?

**Comment by adamghill** [comment]
In https://github.com/adamghill/django-unicorn/blob/main/django_unicorn/static/unicorn/js/unicorn.js#L78 `call` should take either a component name or key as the first argument. https://github.com/adamghill/django-unicorn/blob/main/example/www/templates/www/text-inputs.html#L8 shows an example of how that would work.

I'm going to close this issue for now, but feel free to re-open if it's still unclear or if it doesn't work as expected. 👍

**Comment by jacopsd** [comment]
Didn't know that. Indeed, works great. Thank you.

**Comment by adamghill** [comment]
I added some clarifying documentation around this in 8f9065330f0c29492c3ed188f05997b210b9de95.
