### ISSUE TITLE
When a model and action fire at the same time, the sync input can be lost

### ISSUE THREAD

**Issue by adamghill** [adamghill/django-unicorn#39]
I was not seeing this on local dev with 0.6.0, but it happens when deployed. I am now able to replicate it on local by throttling network responses.

I think I need to merge the syncInput and callMethod actions that fire "at the same time" into the payload array so that the syncInput doesn't get lost.

**Comment by adamghill** [comment]
I think this is fixed in https://github.com/adamghill/django-unicorn/commit/3f082380bf79e21666e3f272f15d13aa10978dd0. Included in 0.6.1.

**Comment by alfonsodav** [comment]
https://www.django-unicorn.com/documentation/examples/todo I was checking your website and there are problems with updating the DOM, occasionally when you add an item to the list it blinks and the newly added item disappears, when you click the Add button again the item appears

**Comment by adamghill** [comment]
Hey @alfonsodav, thanks for letting me know about that regression. I just pushed a new version (0.6.3) which should hopefully fix this once and for all. Let me know if it continues to be a problem!
