### ISSUE TITLE
[Feature] add the posibility of move unicorn/components/<module>.py to a custom place like myapp/views.py

### ISSUE THREAD

**Issue by zodman** [adamghill/django-unicorn#41]
you can define:

```
# settings.py
UNICORN_COMPONENTS_PREFIX  = [
'myapp.views','unicorn.components',
]
```
The locations where the UnicornCompornent will import.

**Comment by adamghill** [comment]
Possible duplicate of https://github.com/adamghill/django-unicorn/issues/15?

I think this could happen around https://github.com/adamghill/django-unicorn/blob/c0238fd55bc66f9c5422fb1f3d4fd3f79c8a2944/django_unicorn/components.py#L614-L615.

**Comment by zodman** [comment]
> Possible duplicate of #15?
> 
> I think this could happen around
> 
> https://github.com/adamghill/django-unicorn/blob/c0238fd55bc66f9c5422fb1f3d4fd3f79c8a2944/django_unicorn/components.py#L614-L615
> 
> .

yes!
