### ISSUE TITLE
[Feature] posibility of change of unicorn: prefix by one custom like uni: on JS

### ISSUE THREAD

**Issue by zodman** [adamghill/django-unicorn#43]

**Comment by adamghill** [comment]
This is an interesting idea! It reminds me of this: https://twitter.com/calebporzio/status/1283446501201649664. I think livewire ended up using `wire` for the attributes. For `django-unicorn` I do try to keep "Explicit is better than implicit." (from https://www.python.org/dev/peps/pep-0020/) in mind and maybe `uni` isn't clear enough for what is happening?

Another (probably way too cutesy) idea would be to use 🦄. So, it would be something like `<input 🦄:model="name"></input>`. Pretty sure that's a bad idea! :)

Another option would be to support `unicorn` or `uni`, but it might make the javascript slightly more complicated in a few places.

**Comment by zodman** [comment]
i thinking about the long of the property. unicorn it is too large ... uni can handle easy ...

**Comment by adamghill** [comment]
@zodman Thoughts? https://github.com/adamghill/django-unicorn/pull/53
