### ISSUE TITLE
How to handle POST request and forms with Django Unicorn

### ISSUE THREAD

**Issue by gschurck** [adamghill/django-unicorn#433]
I don't understand how to manage POST request from forms with Unicorn.

I was used to function based views to handle POST. UnicornView is based on TemplateView, and it seems that it does not handle POST requests.
What is the solution ?
Like if I have a UnicornView component with a form.
Set the top parent as a classic View to handle the POST request here ?

Thanks.

**Comment by adamghill** [comment]
Hello, `Unicorn` doesn't really use GETs/POSTs like a normal web request. If you want to make a change on the server you can use an [action](https://www.django-unicorn.com/docs/actions/) (`Unicorn` wires up an event handler which calls a POST behind the scenes).

I'm going to close this issue, but take a look through the docs and my [example](https://github.com/adamghill/django-unicorn/tree/main/example) app to see a sample.
