### ISSUE TITLE
`updated_` method called twice

### ISSUE THREAD

**Issue by gschurck** [adamghill/django-unicorn#434]
I use a search nested component similar to [this](https://www.django-unicorn.com/docs/child-components/#child-component).
I use `updated_` method to refresh searched data in database each time user type a letter.
The issue is that when I type only one letter, the `updated_` method is called twice, with the old state before I add the new letter and with the new one. Problematic as it doubles database queries :

![image](https://user-images.githubusercontent.com/21091232/188281302-eed3f656-bcd1-4c8c-b53e-1108b27c9738.png)

As a workaround, I added a `last_query` attribute to the view that I check and update on every method call to avoid duplicates.
Is this a normal behavior for the `updated_` method ?
Is there any better way to avoid this double method call ?

Thanks.

**Comment by adamghill** [comment]
Thanks for the bug report. I can replicate this in https://github.com/adamghill/django-unicorn/blob/main/example/unicorn/components/nested/filter.py#L7 and it definitely seems like a bug. I'll take a look and see what might be going on. Your work around makes sense for now until this is fixed.

**Comment by gschurck** [comment]
Okay thanks

**Comment by adamghill** [comment]
This should be fixed with #439 which will be included in the next release. 👍

**Comment by gschurck** [comment]
Perfect 👍🏻
