### ISSUE TITLE
[Bug] Documentation install missing add the csrf_token templatetag

### ISSUE THREAD

**Issue by zodman** [adamghill/django-unicorn#44]
`CSRF token is missing. Do you need to add {% csrf_token %}?`

**Comment by adamghill** [comment]
Do you think I should I add a note to https://www.django-unicorn.com/documentation/installation? Here is that code in the site repo: https://github.com/adamghill/django-unicorn.com/blob/master/www/templates/www/documentation/installation.html.

**Comment by zodman** [comment]
Yes i miss to add the {% csrf_token %} and the #45 appeard. I think on the 

https://github.com/adamghill/django-unicorn/blob/a83f2bf103b13a9d05e359e18a4c6c7e5e5e5b87/django_unicorn/templates/unicorn/scripts.html#L11

```
<script>
    var url = "{% url 'django_unicorn:message' %}";
    Unicorn.init(url, "[% csrf_token %]");
</script>
```

It is needed!

**Comment by adamghill** [comment]
Does this seem like enough? https://github.com/adamghill/django-unicorn.com/commit/a49c4d6c45c8a31c0ef7d1088259660a7069573e

**Comment by zodman** [comment]
i think you can remove the part of the add a newline of code `{% csrf_token %}` it is not necessary!

**Comment by adamghill** [comment]
I think this is ok now. Closing.
