### ISSUE TITLE
Forms do not render correctly for added elements

### ISSUE THREAD

**Issue by lancernik** [adamghill/django-unicorn#452]
At first I would like to say thank you for this framework, it is brilliant and easy to use!

I render the form to each of the objects in the list, but sometimes there are situations where the form does not display properly. After examining an item, you can't even see its source code

Suppose we add an item form for each tag in the todo application. For such an added element, the code contained in form tag completely disappears

`
<div>
    <form unicorn:submit.prevent="add">
        <input type="text" unicorn:model.lazy="task" placeholder="New task" id="task"></input>
    </form>
    <button unicorn:click="add">Add</button>

    <p>
        {% if tasks %}
        <ul>
            {% for task in tasks %}
            <li>{{ task }}

            
            <form unicorn:submit.prevent="add">
                <input type="text" unicorn:model.lazy="name" value="test" id="name"></input>
            </form>
             

            <button unicorn:click="add({{forloop.counter0}})" data-dismiss="modal">Add</button>
          </li>
            {% endfor %}
        </ul>

        <button unicorn:click="$reset">Clear all tasks</button>
        {% else %}
        No tasks 🎉
        {% endif %}
    </p>
</div>
`

[](url)
![Bug](https://user-images.githubusercontent.com/44314663/196352150-4bca91c7-c15d-43ec-b518-ec7bcc6c2ca5.png)

**Comment by VidyaYadavv1519** [comment]
Ensure that each form has a unique ID. The id attribute in your form should be unique for each form on the page. Having multiple forms with the same ID can lead to rendering issues.                                                                                                                                         <form unicorn:submit.prevent="add" id="form_{{forloop.counter0}}">
    
</form>

**Comment by adamghill** [comment]
Sorry @lancernik I definitely missed this issue in the past. Usually this happens because `morphdom` gets a little confused about which elements should be on the page. I have made a few changes recently that should potentially help with this situation or @VidyaYadavv1519's solution of adding a a unique `id` will probably help as well! I'm going to close this, but let me know if you still run into problems.
