### ISSUE TITLE
DirectView doesn't allow u:view attr

### ISSUE THREAD

**Issue by nerdoc** [adamghill/django-unicorn#455]
Long story short: DirectView does not allow the abbreviated `u:view` attribute, only `unicorn:view`. To be consistent, this should be allowed IMHO...
https://github.com/adamghill/django-unicorn/blob/127add9040706db9c8ff21d3084ee5f3089963b6/django_unicorn/components/unicorn_template_response.py#L210

**Comment by adamghill** [comment]
Thanks for the PR. Any chance you can add a test for this as well? Otherwise, I will!

**Comment by nerdoc** [comment]
Sorry, I'm tied up with work ATM..., and don't have Unicorn's testing framework at hand... war just a quick idea, even low prio...
