### ISSUE TITLE
Bug or Update documentation

### ISSUE THREAD

**Issue by iwalucas** [adamghill/django-unicorn#473]
I was going to do a PR, but wanted to check first if this is a bug.

I have a template with 3 `<div>` elements, like this
```
<div id='mydiv1'>
...
</div>
<div id='mydiv2'>
...
</div>
<div id='mydiv3'>
...
</div>
```

And looks like only the first one models gets updated....

I changed it to this and then all models started working:

```
<div id='new wrapper div'>
<div id='mydiv1'>
...
</div>
<div id='mydiv2'>
...
</div>
<div id='mydiv3'>
...
</div>
</div>
```

So if this is working as designed, then lets update the documentation stating that a component needs to have only one root tag. If thats there, I apologize, I couldnt find it.

**Comment by adamghill** [comment]
There is this warning on https://www.django-unicorn.com/docs/templates/. Let me know if it would make sense to put this note somewhere else!

![image](https://user-images.githubusercontent.com/317045/201566217-8ed65239-8451-443b-8134-32558d7bfdeb.jpeg)

**Comment by iwalucas** [comment]
Ah awesome! I was looking for it under the Components section, since there is the first place the template is showed, could we add the same warning there?
thanks!

**Comment by adamghill** [comment]
Makes sense to me! I'll add that in a few. 👍

**Comment by adamghill** [comment]
Added this note to the docs so going to close this issue. Thanks for the suggestion!
