### ISSUE TITLE
Action doesn't work in child component when "parent=view" is applied

### ISSUE THREAD

**Issue by LeeHanYeong** [adamghill/django-unicorn#483]
## Parent component
**Template**
```django
{% load unicorn %}
{% unicorn 'child' parent=view %}
```

## Child component
**Component view**
```python
class ChildView(UnicornView):
    def child_click(self):
        print("child_click")
```
**Template**
```django
{% load unicorn %}
<div>
    <button unicorn:click="child_click">Click</button>
</div>
```

Action does not work in child component when parent=view is applied.
Excluding parent=view, Action works normally.

**Comment by LeeHanYeong** [comment]
It was an error that the name passed to the context of the Django View overlapped with the view.
Parent=view does not work if a specific key is passed to the context before rendering the unicorn component.

**Comment by regoawt** [comment]
> It was an error that the name passed to the context of the Django View overlapped with the view.
> Parent=view does not work if a specific key is passed to the context before rendering the unicorn component.

@LeeHanYeong I've just encountered the same issue. Could you please help me understand what the underlying issue is? Did you actually manage to make it work with `parent=view` included in the child component?
