### ISSUE TITLE
Documentation Website is Down

### ISSUE THREAD

**Issue by emoltz** [adamghill/django-unicorn#487]
<img width="625" alt="Screenshot 2022-12-02 at 11 23 01 PM" src="https://user-images.githubusercontent.com/33405530/205422661-d6deb29b-2f44-4455-a684-753bf523b38c.png">
This is all I see, and it leads me to this site: https://caprover.com/

**Comment by adamghill** [comment]
Yep, thanks for the note. I'm trying to move the docs site but ran into a problem. I'll try to get it fixed asap, but I'm waiting for DNS to propagate.

**Comment by adamghill** [comment]
@emoltz Documentation site should be back up now. Let me know if you run into any other issues.
