### ISSUE TITLE
Dynamically added child components are doesn't work correctly

### ISSUE THREAD

**Issue by towan912** [adamghill/django-unicorn#499]
Dynamically added child components are cannot call parent component functions or events.
If the parent component is not inherited, it will render correctly.

I'm setting up morphdom.

The version of the unicorn is 0.49.2.

**Comment by towan912** [comment]
I'll have to look into this in more detail, but I suspect the problem is that the #430 fix creates a new UnicornView without using the View of the parent component that was passed to the child component.

**Comment by adamghill** [comment]
I think this should be fixed by 0.58.0 of `Unicorn` which drastically improves child components so I'm going to close it. If it is still a problem feel free to re-open this and create a failing test or small example in the `example` app of this repo to replicate, though. Thank you!
