### ISSUE TITLE
Customize unicorn url.

### ISSUE THREAD

**Issue by peacememories** [adamghill/django-unicorn#501]
Currently, it does not seem to be possible to change which url Unicorn accesses when actions are triggered. This is a problem for us since our Django app does not run at the root of its domain.

Possible solutions:
* Add a setting, e.g. `BASE_URL` that allows specifying the base url of the unicorn routes.
* Use a route name for the unicorn route and do a reverse-lookup via that.

**Comment by adamghill** [comment]
Woohoo, I'm glad this is working for you! :)
