### ISSUE TITLE
Using dict as component fields can break checksums

### ISSUE THREAD

**Issue by bazubii** [adamghill/django-unicorn#516]
Repo: have a component with a field that is a dict with keys that are str of ints. Ie `{'34':'bar','4':'foo'}`. Next, update that dict by adding a new key that would result in a different dict key order if they were sorted. In python, it won't sort them, they stay in insertion order. On the client side, at least in chrome, when response.json() is called, that reorder's the dict keys. This results in an invalid checksum the next time an update happens. See [SO post](https://stackoverflow.com/questions/6993645/ordered-jsonobject) for example on javascript reordering dict keys automatically when parsing json. 

Result: Dictionaries are dangerous to use in component data. 

Possible fix, don't use response.json in the unicorn response parsing? Maybe use a different json parser?

Workaround I'm using for now: Don't use dicts, maybe use lists of k, v tuples if required.

**Comment by bazubii** [comment]
Another fix would be to make the checksum logic not care about order somehow.... that keeps it in python instead of js, but would require more complicated scanning of the data for dicts.

**Comment by adamghill** [comment]
If we always sorted the dictionary in Python by key before serializing, would that mitigate this problem?

**Comment by bazubii** [comment]
> If we always sorted the dictionary in Python by key before serializing, would that mitigate this problem?

Maybe? I'm not sure what sort order the js json de-serializer is using. We'd have to match that. Since the dict would be reordered by that no matter what order python used. It appears people say that it doesn't sort them unless the key is a str of an int.... but I don't know if that's reliable. 

Another more complicated way would be to automatically turn dicts to lists of k, v tuples, then undo that after json deserialization in unicorn's js.

**Comment by adamghill** [comment]
Because this crosses both Python + JavaScript, writing an automated test for this is tricky, but that seems like maybe a good first step? It'd be nice to have a test to replicate this issue first, then we can try a few approaches and see what works best?

**Comment by bazubii** [comment]
Sounds reasonable. I can't do it ATM but I can try to get to it this week. It's also possible like the SO post says that it's dependent on the browser, which may suck for automation as well, but worth trying and seeing.

**Comment by adamghill** [comment]
I think I have a way forward for this in PR #572.

**Comment by adamghill** [comment]
This should be fixed when 0.54.0 is released., so closing this. Please re-open if 0.54.0 doesn't work for some reason.
