### ISSUE TITLE
Using variable named {{ update }} fails with Polling

### ISSUE THREAD

**Issue by dancaron** [adamghill/django-unicorn#519]
```
<!-- polling-every-five-seconds.html -->
<div unicorn:poll-5000="get_updates">
  <input unicorn:model="update" type="text" id="text" />
  {{ update }}
</div>
```

I think the namespace {{ update }} might be problematic. When I rename it in the template, view and view function, polling works as expected.

**Comment by dancaron** [comment]
Or, maybe the variable needs to be initialized in mount() as well as a property on the View.

**Comment by dancaron** [comment]
This ultimately might be a documentation update. (Needing to initialize polling variables inside of mount()?)

**Comment by adamghill** [comment]
Yeah, I tend to use `mount` to initialize variables like this. What updates would be useful for the docs to make that more clear?
