### ISSUE TITLE
`request.user.is_authenticated` is False in Unicorn template but user is authenticated in Django

### ISSUE THREAD

**Issue by gschurck** [adamghill/django-unicorn#525]
On my website when I login, in nested Unicorn template `request.user.is_authenticated ` returns False, but in normal Django template it is True.
Is it possible to check if user is authenticated in Unicorn view ?
Thanks.

**Comment by gschurck** [comment]
It works finally, don't knwo why it wasn't working earlier.

**Comment by adamghill** [comment]
Hmm, that's weird. If you can replicate later, let me know!
