### ISSUE TITLE
DOCS: Rename `django-idom` to `reactpy-django`

### ISSUE THREAD

**Issue by Archmonger** [adamghill/django-unicorn#531]
`django-idom` has rebranded itself to `reactpy-django` as of today. The docs should be updated to reflect this.

See here for traceability
- https://github.com/adamghill/django-unicorn/pull/356
- https://github.com/adamghill/django-unicorn.com/pull/21

**Comment by adamghill** [comment]
Thanks for the heads up. This has been updated. 👍
