### ISSUE TITLE
Checkbox unable to get property checked

### ISSUE THREAD

**Issue by algameko** [adamghill/django-unicorn#540]
### Discussed in https://github.com/adamghill/django-unicorn/discussions/539

<div type='discussions-op-text'>

<sup>Originally posted by **algameko** June  5, 2023</sup>
I'm trying to make a filter on a table with django-unicorn component with the following code:

  
```
table-search.html

<input unicorn:click.debounce-1000="update_search({{ subcategory.id }}, $event.target.checked)" type="checkbox" id="subcat_{{ subcategory.id }}">

```

```
table-search.py

class TableSearchView(UnicornView):
    elements = []
    filter_dict = {}
    
    def mount(self):
        initial filter on a table etc.

    def update_search(self, id_subcat=None, checked=None):
        self.filter_dict[id_subcat]=checked

```

Component work on mount but there's now way to obtain $event.target.checked, it always return None.
</div>

**Comment by adamghill** [comment]
In https://github.com/adamghill/django-unicorn/discussions/539 you mentioned you fixed this with a code change. But, let me know if `unicorn` could handle this better. Otherwise, I'll close this issue. 👍

**Comment by adamghill** [comment]
Closing because a solution was found.
