### ISSUE TITLE
Feature request: Loading target multiple elements

### ISSUE THREAD

**Issue by regoawt** [adamghill/django-unicorn#542]
Hi Adam,
 
I have a component where there are multiple action elements that can enter a loading state. I would like to target a subgroup of these elements when using the `unicorn:loading` tag. 

This subgroup of elements is created in a for loop e.g
```
{% for project in filtered_projects %}
    <li>
        <a u:click="select_project('{{ project }}')" id="select-project-{{ project }}" href="#">
            <div>
                <p>{{ project }}</p>
            </div>
        </a>
    </li>
{% endfor %}
```
Therefore I cannot simply use the same `id` or `unicorn:key` for all of them and target that, as this causes errors with other functionality within the component. 

As you can see in the above template snippet, the `id`s of the elements have the pattern 'select-project-*' and so I wonder whether it would be possible to add some kind of wildcard functionality to target multiple elements? I've had a look at the code and it seems like some minor (possibly wishful thinking) modifications to `eventListeners.js` could achieve this.

Let me know your thoughts, or if you need anymore information. If there are no immediate red flags and you are keen, I'd be happy to try submit a PR.

Lastly, thank you for creating django-unicorn, it's great!

**Comment by adamghill** [comment]
Hey! This is an interesting idea. I'd be interested in a PR that handles an asterisk as a wildcard if you are able.

**Comment by regoawt** [comment]
Great! Will have a go at it.

**Comment by regoawt** [comment]
@adamghill I'll close this now that the PR is in, thanks for that. Could I be added to the contributors on the readme please, for code and tests I guess? 😄 Cheers

**Comment by adamghill** [comment]
@all-contributors please add @regoawt for code and tests

**Comment by adamghill** [comment]
Done! Thanks for reminding me!
