### ISSUE TITLE
(de)activating a component

### ISSUE THREAD

**Issue by krzysztofjeziorny** [adamghill/django-unicorn#549]
Sorry for asking a possibly dumb question, but is a scenario like this possible with Unicorn?: I've got multiple components placed in one template, they are initially inactive, and activated when clicked on a button/link, also deactivating the other components, so only current one stays visible and operative? Are parent/child components meant for such behavior?

For now I placed mine in a Bootstrap's [tabbed interface](https://getbootstrap.com/docs/5.3/components/navs-tabs/#javascript-behavior), but would like to do it differently.

Thanks!

**Comment by adamghill** [comment]
Hello! You can take a look at my [child components example](https://github.com/adamghill/django-unicorn/blob/main/example/unicorn/templates/unicorn/nested/table.html) to see what I've gotten working although I don't think I've tried exactly what you are looking for. I'd love to hear feedback if it doesn't seem to work. If you make a PR with some example code I can try to get things working!

**Comment by adamghill** [comment]
Closing this because child components are the way to solve this use case. Thanks!
