### ISSUE TITLE
Possible directory error in default examples

### ISSUE THREAD

**Issue by stukev** [adamghill/django-unicorn#57]
Hi. I've created an empty django project to test unicorn. But somehow the default instructions don't seem to work and cause a template not found error. Here's what I've done:

1. Created a new django project in pycharm
2. pip install django-unicorn
3. Added "django_unicorn", to the INSTALLED_APPS
4. Created an empty base.html file and made it viewable in the browser
5. Added path("unicorn/", include("django_unicorn.urls"))
6. Added {% load unicorn %} to the top of base.html
7. Added {% unicorn_scripts %} right underneath in base.html
8. Ran python manage.py startunicorn hello-world
9. Added {% unicorn 'hello-world' %} at the bottom of base.html

After this last step 9 it starts to break and throws a TemplateDoesNotExist error:
`django.template.loaders.filesystem.Loader: /home/user/uniplayground/templates/unicorn/hello-world.html (Source does not exist)`

In my project folder the hello-world.html file generated by step 8 is located under:
`/home/user/uniplayground/unicorn/templates/unicorn/hello-world.html`

Am I doing something wrong or does the startunicorn command not generate the files into the right structure?

Edit: Moving the HTML file to the template folder that django is looking in seems to work. While leaving the python file in the generated folder structure.

**Comment by adamghill** [comment]
Thanks for the reported issue! The error message is a little confusing, but the management command creates all of the components in a separate `unicorn` folder/app, so it requires adding `unicorn` to the `INSTALLED_APPS` setting for Django to "know" about that app and look in its template folder. I'm not in love with that requirement, but if nothing else I should add a note to the installation instructions and to https://www.django-unicorn.com/documentation/cli to make it more clear. Note that I would like to make it configurable what apps are searched for components, but I haven't done it, yet.

But, add in `unicorn` to the INSTALLED_APPS and let me know if that fixes your problem! Thanks again for the report. I'd love to hear other issues you run into while testing. :)

**Comment by adamghill** [comment]
@stukev There is a note in the documentation that details that `unicorn` needs to be added for the template to be found: https://github.com/adamghill/django-unicorn.com/blob/1e36752/www/templates/www/documentation/components.html#L22-L24. And there will now be more instructions after running `startunicorn`: https://github.com/adamghill/django-unicorn/commit/4d56136bf276384719945e124ba1f6f9568ab72f.

Hopefully those are good steps to clarifying this for others. I'm going to close this, but feel free to re-open or add in other ideas to make the experience better!
