### ISSUE TITLE
Data inside dictionary gets manipulated 

### ISSUE THREAD

**Issue by hamidrabedi** [adamghill/django-unicorn#575]
So i have this unicorn view:

```py
class ProductView(UnicornView):
    reviews: QuerySet[Review] = None
    product: Type[Product] = None
    # review: Type[Review] = Review()
    # form_class = ReviewForm
    reviewing = False
    is_writing = False
    title = ""
    message = ""
    rate = int()
    form_errors = {}

    def mount(self):
        self.reviews = self.product.reviews.get_not_deleted_reviews().get_verified_reviews()\
            .values(
                "rate",
                "title",
                "created",
                "message",
            )

    def edit(self):
        self.reviewing = True

    def writing(self):
        self.is_writing = True

    def create_form(self):
        data = {
            "title": self.title,
            "message": self.message,
            "rate": self.rate,
            "product": self.product,
            "user": self.request.user
        }
        form = ReviewForm(data)
        if form.is_valid():
            form.save()
            self.form_errors = {}
            messages.success(self.request, _("Your comment submitted successfully and will be published once it gets verified"))
            self.is_writing = False
            self.reset()
        else:
            self.form_errors = {str(i.label):i.errors for i in form if i.errors}

    def submit(self):
        self.create_form()
```

and in my html:
```
{{form_errors}}
{% if form_errors %}
<div class="alert alert-danger">
    <strong>{% trans 'Please fix the errors:' %}</strong>
    {% for field, error_list in form_errors.items %}
        <p>{{ field }}:</p>
        <ul>
            {% for error in error_list %}
                <li>{{ error|escape }}</li>
            {% endfor %}
        </ul>
    {% endfor %}
</div>
{% endif %}
```

and everything works fine  when i submit the form (i mean shows errors properly) :
![image](https://github.com/adamghill/django-unicorn/assets/92696830/117a6f0a-a339-4ab6-9397-e37f8b786ad5)

and when i change the value inside one of my inputs the values of dictionary (which are list of strings) just gets removed but the keys remain:
![image](https://github.com/adamghill/django-unicorn/assets/92696830/b4d4fcb0-dbb8-4478-b738-4b139b7456a0)

**Comment by winrid** [comment]
Writing some TypedDict classes for `form_errors` and then defining the type should fix it.

**Comment by adamghill** [comment]
Hmm, so I'm not sure I understand what exactly is happening here, but a few thoughts:

Use `None` for the initial value of `form_errors` or use `mount` to create a new `dictionary` of `form_errors` if needed. This will remove a mutable class attribute which you almost certainly aren't intending for.

Instead of:
```python
class ProductView(UnicornView):
    ...
    form_errors = {}
    ...
```

```python
class ProductView(UnicornView):
    ...
    form_errors = None
    
    def mount(self):
        self.form_errors = {}  # this is optional if you need it
```

You could also look into using the `form_class` in your view which should handle some of the form logic you are doing manually: https://www.django-unicorn.com/docs/validation/.

I'm going to close this for now, but let me know if you are still running into problems and can make a reproducible test case that I can I work on. Thanks!
