### ISSUE TITLE
Documentation regarding Child Components wrong?

### ISSUE THREAD

**Issue by hendi** [adamghill/django-unicorn#576]
The [documentation](https://www.django-unicorn.com/docs/child-components/) states that "the child component must pass in a parent keyword argument with the parent’s component view" using `parent=view`.

However, the following code seems to indicate otherwise:

**test_parent.py**
```python
from django_unicorn.components import UnicornView

class TestParentView(UnicornView):
    def foo(self):
        print("foo() from parent")
```

**test-parent.html**
```html
{% load unicorn %}
<div>
    <div style="width:200px;height:200px;margin:10px;background-color:#aaffaa" unicorn:click="foo()">
        Parent
    </div>

    {% unicorn "test-child" parent=view %}
</div>
```

**test_child.py**
```python
from django_unicorn.components import UnicornView

class TestChildView(UnicornView):
    def mount(self):
        print("child mounted, parent=", self.parent)

    def foo(self):
        print("foo() from child")
```

**test-child.html**
```html
<div>
    <div style="width:100px;height:100px;margin:10px;background-color:#ffaaaa" unicorn:click="foo()">
    Child
    </div>
</div>
```

Opening the page in the browser, the child prints to the console `child mounted, parent= <django_unicorn.components.unicorn_view.UnicornView object at 0x7f524df293d0>` so the parent isn't the actual parent component, but the general `UnicornView`. Further, clicking on either box doesn't print anything. Clicking on the parent box shows only a call to `POST /unicorn/message/test-parent HTTP/1.1" 304 0` but doesn't print anything; clicking on the child box doesn't do anything.

However, if I remove the `parent=view` from the test-parent.html file, it works as expected:

1. clicking the boxes prints to the terminal
2. the child prints to the console: `child mounted, parent= <myapp.components.test_parent.TestParentView object at 0x7f524f1e7690` so its parent is the actual `TestParentView` component.

**Comment by hendi** [comment]
It's getting weird... I created a simple test case in this repo in the examples dir, and there it works as expected/with `parent=view` set. I've checked my local project where the issue persists, and I'm at 0.54.0 there 🤔

**Comment by adamghill** [comment]
I'm going to investigate a little and see what might be going on!

**Comment by adamghill** [comment]
So, originally setting `parent=view` _was_ a requirement, but https://github.com/adamghill/django-unicorn/blob/2c17c905dcd5c019d86f9e3812ef048fca91fbea/django_unicorn/templatetags/unicorn.py#L142-L144 got added by a contributor which sets the parent automatically. I could remove that part from the documentation?

Although, I am a little confused what is happening in your code when you use `parent=view`. I've been trying to replicate that in my testing, but haven't been able to, yet. If you have sample that would be super helpful!

**Comment by adamghill** [comment]
Thanks for this report! I ended up removing the mention of `parent=view` when loading child components in b308459 so this doesn't trip up others in the future.
