### ISSUE TITLE
Request is `None` when child calls a parent's method

### ISSUE THREAD

**Issue by hendi** [adamghill/django-unicorn#579]
```python
class ParentView(UnicornView):
    def mount(self):
        print("parent mount: request=", self.request)

    def foo(self):
        print("parent foo: request=", self.request)


class ChildView(UnicornView):
    def mount(self):
        print("child mounted, parent=", self.parent)

    def foo(self):
        print("calling parent.foo()")
        self.parent.foo()
```

Calling the child's `foo` method (e.g. by clicking a button in the child component) prints in the terminal:

```
parent mount: request= <WSGIRequest: GET '/parent'>
child mounted, parent= <unicorn.components.parent.ParentView object at 0x7fe536d3ad90>
calling parent.foo()
parent foo: request= None   # <-- request is None
```

If the parent's `foo` method is called directly from the component, its request is set.

**Comment by adamghill** [comment]
Thanks for reporting this! I will check into what might be going on here. I have a hunch I might know how to resolve this. 👍

**Comment by adamghill** [comment]
I think https://github.com/adamghill/django-unicorn/pull/583 should fix this problem. Let me know if you want to verify against `main` or if I should just release a new version for you to check.

**Comment by hendi** [comment]
I've checked and can confirm that it works, thanks a lot! (No need for a new release, I'm fine with targeting `git main`)
