### ISSUE TITLE
Component does not update its parent's state

### ISSUE THREAD

**Issue by imankulov** [adamghill/django-unicorn#592]
When I update the state of a parent component, I expect it to reflect these changes. However, unless I update something in the component itself, the changes are not propagated back to the client.

## Sample setup

There are two components: a wrapper with a counter and a button that updates the counter. When I click the button, I expect the counter to be updated. However, the server returns a 304 status code and an empty response, and the UI is not updated.

- Wrapper Python: [link](https://github.com/imankulov/django-unicorn-demo/blob/main/django_unicorn_bug/components/wrapper.py)
- Wrapper HTML: [link](https://github.com/imankulov/django-unicorn-demo/blob/main/django_unicorn_bug/templates/unicorn/wrapper.html)
- Button Python: [link](https://github.com/imankulov/django-unicorn-demo/blob/main/django_unicorn_bug/components/button.py)
- Button HTML: [link](https://github.com/imankulov/django-unicorn-demo/blob/main/django_unicorn_bug/templates/unicorn/button.html)

## More information

- Demo repository: [link](https://github.com/imankulov/django-unicorn-demo)
- Video demonstrating the issue: [link](https://www.loom.com/share/c25a8a4395474c0ea00c785db13f7c84)

**Comment by adamghill** [comment]
There is a feature in `Unicorn` which sends back a 304 if the rendered content stays the same to reduce network bandwidth. This issue presented a situation where a child component didn't change, but the parent did -- with the PR #595 the parent component will re-render as expected.

**Comment by imankulov** [comment]
Thank you for the fix! I can confirm that the PR #595 fixes the issue 👍

**Comment by wplct** [comment]
Demo repository: [link](https://github.com/imankulov/django-unicorn-demo)

Modify this demo to django-unicorn==0.58, can still reproduce the error of value not changing.
