### ISSUE TITLE
Add the possibility to set django variables as action parameters. 

### ISSUE THREAD

**Issue by nyradr** [adamghill/django-unicorn#60]

**Comment by adamghill** [comment]
@nyradr This is a great idea! I have an idea of how this _could_ work, so I'll try to get something into the next release.

**Comment by adamghill** [comment]
@nyradr Actually, could you give me some sample code of what you are trying to do?

What I thought you were asking for does seem to work fine in my testing:

```python
class TestView(UnicornView):
    test = "asdf"
    result = "hjkl"

    def do_something(self, str):
        self.test = str
```

```html
<div>
  <input unicorn:model="test" type="text" id="test">
  <button unicorn:click='do_something({{ result }})'>do something!</button>
</div>
```

Or were you trying to do something else?

**Comment by nyradr** [comment]
I was thinking of doing something like :

```python
class TestView(UnicornView):
    objs = ModelObject.objects.all()

    def delete(self, obj):
        obj.delete()
        objs = ModelObject.objects.all() 
```

```html
<ul>
    {% for obj in objs %}
        <li>
            <p>{{ obj }}<p>
            <button unicorn:click='delete(obj)'>delete</button>
        </li>
    {% endfor %}
</ul>
```
As long as I can send object (or the object id) to the function and do something like CRUD it's fine.

**Comment by adamghill** [comment]
Ah, ok. So, this would work fine:

```
class TestView(UnicornView):
    objs = ModelObject.objects.all()

    def delete(self, id):
        obj = ModelObject.objects.get(id=id)
        obj.delete()
        self.objs = ModelObject.objects.all() 
```
```
<ul>
    {% for obj in objs %}
        <li>
            <p>{{ obj }}<p>
            <button unicorn:click='delete({{ obj.id }})'>delete</button>
        </li>
    {% endfor %}
</ul>
```

I might be able to figure out how to pass in the model object itself to an action, but for now support is mostly limited to basic Python primitives (int, str, uuid, list, set, tuple, dict, float, datetime).

**Comment by adamghill** [comment]
I spent a little bit of time trying to see if passing in just a model to an action might be doable, but I don't see an easy way to do it. Since it sounds like passing in an `id`/`pk` to the action works for your purposes, I'm going to close this, but feel free to re-open it or create a new issue if needed.

**Comment by nyradr** [comment]
Effectively. That works that way.
Thank you for your help on this.
