### ISSUE TITLE
Sometimes event listeners fire the wrong events

### ISSUE THREAD

**Issue by imankulov** [adamghill/django-unicorn#608]
## What happens

- After updating the component, it is possible for event listeners to fire the wrong events. These events may belong to a different component.
- This issue occurs because Django-unicorn runs event handlers for all components, assuming that two components cannot share HTML nodes (event.target).
- However, it is possible for a newly rendered component to "inherit" HTML nodes from a previously rendered component if we hide the first component and show the second one.
- When this happens, the morphdom algorithm, in an attempt to apply minimal changes, may preserve a node from the first component and render it for the second component.
- Consequently, when clicking on the HTML node of the second element, the handler of the first hidden component is actually fired.
 
## Workaround

The workaround is to assign unique IDs to HTML components with event handlers so that morphdom rebuilds them from scratch.

## Suggested "proper" solution

One possible solution is for the element with an attached event to dynamically find its parent component. This way, instead of having as many event handlers as we have components on the page, we can have a single event handler that detects if the element belongs to a Unicorn component. It can then find the Unicorn parent, the event name, and the parameters.

However, I am not sure about it.

## Example

You can see the example of the wrong behavior in the [example/wizard](https://github.com/imankulov/django-unicorn/tree/example/wizard) branch of my fork.

**Comment by imankulov** [comment]
I recorded a video outlining the issue: https://www.loom.com/share/24c2afa320654db4a7a52728595f4073

**Comment by adamghill** [comment]
>The workaround is to assign unique IDs to HTML components with event handlers so that morphdom rebuilds them from scratch.

I'm experimenting with adding `node.getAttribute("unicorn:id") ||` to https://github.com/adamghill/django-unicorn/blob/main/django_unicorn/static/unicorn/js/morphers/morphdom.js#L18-L31 so it uses the generated component id as part of the morph. It fixed one problem, but I'm still running into other issues with the branch so I'm still testing.

>single event handler that detects if the element belongs to a Unicorn component

I started going down this road in a prototype, but ended up backing into what happens in `addActionEventListener`. It would be nice if there were only one event listener that could figure out what to do based on the target element.

**Comment by adamghill** [comment]
@imankulov I added your wizard example to https://github.com/adamghill/django-unicorn/pull/600 because I think you fixed one of the issues with that PR. I have made a few other fixes and it _mostly_ works now, although I'd love some feedback if it looks better for you as well. Thanks!

**Comment by adamghill** [comment]
These fixes got merged into 0.58.0. Thanks for the excellent error report!

**Comment by adamghill** [comment]
@all-contributors please add @imankulov for code
