### ISSUE TITLE
Not Working on Public Pages When Unauthenticated?

### ISSUE THREAD

**Issue by winrid** [adamghill/django-unicorn#614]
Here: https://sidewaysdata.com/

Try to change filters.

In console:
```
utils.js:72 Uncaught Error: CSRF token is missing. Do you need to add {% csrf_token %}?
    at getCsrfToken (utils.js:72:9)
    at send (messageSender.js:40:44)
    at later (delayers.js:22:14)
```

When logged in it's fine.

Homepage has:

```
{% load cdnstaticfiles %}
{% load unicorn %}
{% csrf_token %}

{% block scripts %}
    {% unicorn_scripts %}
{% endblock %}
```

Component loaded with:

```
{% unicorn 'find_events' %}
```

Is there some way to turn off the CSRF check for public stuff? For example this component doesn't change any data. There's no reason for it to require CSRF IMO.

I see in the browser I have no cookies:

```
document.cookie
''
```

Not sure why this is?

After I visit the login page once, **then** I get a `csrfToken`.

If this is the default behavior and there is some kind of fix, I think it should be at least called out in the docs (unless I missed something...). Thanks.

**Comment by winrid** [comment]
Ohkay, adding this to my view fixes it:

```
@ensure_csrf_cookie
```

I think maybe we should call this out in the docs for public pages? Otherwise people will try to use django-unicorn on a public page, see it not work, and think it's broken.

**Comment by adamghill** [comment]
There is [this discussion](https://github.com/adamghill/django-unicorn/discussions/601) where a few other solutions are talked about. But, adding something to the docs would be an easy fix for now. What do you think?

**Comment by winrid** [comment]
@adamghill I think that's a good start! I also think a component level override for the CSRF token would be the ideal longer term solution for read only components.

**Comment by adamghill** [comment]
I couldn't exactly replicate the behavior you described, but I wonder if adding `@ensure_csrf_cookie` to the POST endpoint would be helpful?

**Comment by winrid** [comment]
No that won't help. Unicorn throws an error on the client before sending the request.

1. Use incognito
2. Ensure not signed in to app
3. Clear cookies
4. Visit public page
5. Verify in console - document.cookie is empty
6. Try to interact with component - throws error

**Comment by adamghill** [comment]
I don't get the CSRF error you see. I get this:
<img width="693" alt="image" src="https://github.com/adamghill/django-unicorn/assets/317045/8bcbfe6d-a231-48fc-b521-7167e524522b">

But, yeah, you are right the `@ensure_csrf_cookie` on the `Unicorn` endpoint makes it work for the second Unicorn interaction, but not the first because the cookie needs to be set beforehand. Still slightly better experience, but not great.

**Comment by winrid** [comment]
Hey Adam - If you don't have a cookie then how is it even making the request? You must have the csrf token in the page somehow?

The Unicorn JS throws if there is no CSRF token.

**Comment by winrid** [comment]
It turns out that I'm dumb and the csrf_token block was not being rendered since it wasn't defined in a block from the extended template, and there are no warnings from Django when you do that.

**Comment by adamghill** [comment]
No worries! I don't see any harm so I added `@ensure_csrf_cookie` to the `Unicorn` endpoint anyway. I also added a section to troubleshooting.md to hopefully help anyone else that runs into this issue.
