### ISSUE TITLE
Docs for JSONField

### ISSUE THREAD

**Issue by winrid** [adamghill/django-unicorn#616]
Can we document how to use `models.JSONField` properly?

It seems that right now the types get mangled - ints and floats become `str` after any update happens.

I'm guessing we just need to define encoders/decoders to make it work properly but AFAIK this is not in the docs.

**Comment by adamghill** [comment]
Hmm, I don't think I've ever tried a `JSONField` with `Unicorn`. Theoretically it should be straight-forward to deal with, but I'll let you know how it goes.

**Comment by winrid** [comment]
In sideways data you can search for the unicorn bug in the weather component. I have a patch there to re-fresh the JSON after a page event because it gets mangled.

**Comment by adamghill** [comment]
I took a look at the weather component in sidewaysdata, but without a weather API key I couldn't do an end-to-end test unfortunately. However, I did add an example to https://github.com/adamghill/django-unicorn/pull/625.

Here's a video of that JSONField working AFAICT when creating a new object and then updating JSON in a field:
https://github.com/adamghill/django-unicorn/assets/317045/ee63164a-ee62-49ee-914a-c530376a5348

But, I might be missing something else. If you can look at #625 push an example that doesn't work as expected that'd be much appreciated.

**Comment by winrid** [comment]
Hey @adamghill don't get me wrong, they work, it's just my floats/ints deep in the object got transformed into strings. I'll see about testing it again this week.

**Comment by winrid** [comment]
@adamghill I tested this again. I couldn't reproduce the error I remember, but I was able to find and fix the actual issue which was modifying a cached object by reference - sorry about that.

**Comment by adamghill** [comment]
No worries! Glad to hear it's all good.
