### ISSUE TITLE
Fail Hard on Missing Key

### ISSUE THREAD

**Issue by winrid** [adamghill/django-unicorn#618]
Opinion: When there are multiple components in a page/parent component, require "key". Otherwise just the first component is used over and over and its state is reused. I think throwing an error would be preferable to creating this kind of bug.

**Comment by adamghill** [comment]
Every component is an instance of the view with a unique identifier already. Component keys are used to get around some quirks with how the DOM diffing algorithm works. However, I have a fix in another PR that removes the need for component key altogether.

I'll keep this issue open for right now, but link the other PR to this and then close it once component key are not required anymore.

**Comment by adamghill** [comment]
The PR I mentioned is https://github.com/adamghill/django-unicorn/pull/620. However, even though it removes the need for `unicorn:key` for DOM merging, they are still useful for partial updates and targeting a particular component so I can't remove them completely. Closing this issue, let me know if you have other questions about `unicorn:key` in the future.
