### ISSUE TITLE
Unicorn setup during the Django tutorial breaks the tutorial rocket

### ISSUE THREAD

**Issue by deliciouslytyped** [adamghill/django-unicorn#627]
After completing the django tutorial at https://docs.djangoproject.com/en/4.2/intro/tutorial01/ up to "Now that the server’s running, visit http://127.0.0.1:8000/ with your web browser. You’ll see a “Congratulations!” page, with a rocket taking off. It worked!", adding `path("unicorn/", include("django_unicorn.urls"))` to urls.py (following the unicorn setup tutorial) breaks the "The install worked successfully! Congratulations!" rocket and instead gives:

```
Page not found (404)
Request Method: GET
Request URL: http://127.0.0.1:8000/
Using the URLconf defined in myproj.urls, Django tried these URL patterns, in this order:
    admin/
    unicorn/
The empty path didn’t match any of these.
You’re seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
```

Django 4.2.7
Unicorn 0.57.1

**Comment by deliciouslytyped** [comment]
This might not be a real issue. I'm just new. It might be that adding *any* new URLs to the configuration disables the default landing (or I suppose takeoff) page.

**Comment by deliciouslytyped** [comment]
Issue invalid, seems to be the case: https://github.com/django/django/blob/656192c2c96bb955a399d92f381e38fe2254fe17/django/views/debug.py#L622

**Comment by adamghill** [comment]
Yep! This will happen for any new URL and is by design in Django. No worries! 👍
