### ISSUE TITLE
Using requests library inside of a UnicornView

### ISSUE THREAD

**Issue by korbad3v** [adamghill/django-unicorn#646]
Using the working Todo example as a base, I'm trying to make an api call from inside the UnicornView to append items to the list. Unfortunately I'm just getting 504 timeouts back. The api works, tested from the python console using the same setup (not counting unicorn).

My question is, is this possible at all? 

Or is the UnicornView expecting not to wait around for a response from an api?

**Comment by adamghill** [comment]
I assume you are calling the API from an method in `UnicornView`? I don't know of any reason why that wouldn't work. Does the API timeout and give a 504 response or are you seeing that in the JavaScript console from Unicorn?

>Or is the UnicornView expecting not to wait around for a response from an api?

There are no async parts of Unicorn so it is all synchronous and will wait as long as needed.

I'm going to close this, but feel free to open it back up with a sample repo or test that replicates the problem. Thanks!
