### ISSUE TITLE
Add code coverage badge to repo

### ISSUE THREAD

**Issue by adamghill** [adamghill/django-unicorn#692]
Code coverage is already set up, but something needs to get the data for the badge. 

Some things to look into:
- https://smarie.github.io/python-genbadge/
- https://github.com/marketplace/actions/coverage-py-badge

**Comment by mihrab34** [comment]
I can work on this

**Comment by adamghill** [comment]
Awesome! I've never set this up before, but I'm excited to see how it works! 🥳

**Comment by mihrab34** [comment]
@adamghill  I'm having some kind of error when I run `poetry run python manage.py migrate`. I'm using Windows

> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\django-unicorn-stLXlbqC-py3.11\Lib\site-packages\django\apps\config.py", line 210, in create
>     app_module = import_module(app_name)
>                  ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'example'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\user\Desktop\djangonauts\django-unicorn\example\manage.py", line 21, in <module>
>     main()
>   File "C:\Users\user\Desktop\djangonauts\django-unicorn\example\manage.py", line 17, in main
>     execute_from_command_line(sys.argv)
>   File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\django-unicorn-stLXlbqC-py3.11\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
>     utility.execute()
>   File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\django-unicorn-stLXlbqC-py3.11\Lib\site-packages\django\core\management\__init__.py", line 416, in execute
>     django.setup()
>   File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\django-unicorn-stLXlbqC-py3.11\Lib\site-packages\django\__init__.py", line 24, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\django-unicorn-stLXlbqC-py3.11\Lib\site-packages\django\apps\registry.py", line 91, in populate
>     app_config = AppConfig.create(entry)
>                  ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\django-unicorn-stLXlbqC-py3.11\Lib\site-packages\django\apps\config.py", line 212, in create
>     raise ImproperlyConfigured(
> django.core.exceptions.ImproperlyConfigured: Cannot import 'example.books'. Check that 'books.apps.Config.name' is correct.

**Comment by mihrab34** [comment]
Fixed it!

**Comment by adamghill** [comment]
Should we add/update instructions somewhere for what you ended up doing?

**Comment by mihrab34** [comment]
I just had to re-confirm my Python path, restart my computer and open the project with Pycharm.
