### ISSUE TITLE
Set up issue template

### ISSUE THREAD

**Issue by adamghill** [adamghill/django-unicorn#694]
I'm tempted to convert all issues to discussions to remove the confusion between Issue, PR, and Discussion. However, I'm not sure that is a good idea.

Another approach is to create an issue template which makes it more clear what is required before creating an issue:
- PR that reproduces the issue using this repository's example site
- a failing test case
- a sample repository and steps to reproduce the issue

I don't want to prevent people from raising up issues they find, but it can be hard to replicate bugs sometimes because there are so many variables at play, i.e. Django settings, different browsers, different versions of Python, etc.

**Comment by mihrab34** [comment]
I could pick this up whilst I wait for the review on the other PR 🤷🏽‍♀️.   Check this out

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by adamghill** [comment]
Sounds good to me! 👍
