### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by adamghill** [adamghill/django-unicorn#698]
Looking at https://gist.github.com/PurpleBooth/b24679402957c63ec426 (although most of that is a CoC and I already have a separate CoC already) and https://github.com/django/django/blob/main/CONTRIBUTING.rst (although that links to _a lot_ of other docs about how to contribute to Django).

@mihrab34 Do you have an example CONTRIBUTING file that you seen in the past and liked?

**Comment by mihrab34** [comment]
@adamghill I liked this one Async API uses for their projects [https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

**Comment by adamghill** [comment]
THis got merged in, so closing this.
