### ISSUE TITLE
The django-unicorn.com domain wasn't renewed

### ISSUE THREAD

**Issue by frnidito** [adamghill/django-unicorn#714]
...and this makes the website and documentation not accessible.

At the moment, when going there, only the following can be seen:

![Screenshot 2024-07-18 at 12 04 16](https://github.com/user-attachments/assets/3e82f4b8-ef25-4371-a3cc-e88ab3a94fe8)

**Comment by adamghill** [comment]
Yikes! Sorry about that, I just renewed it. Is it looking better for you?

**Comment by frnidito** [comment]
I works now :)

Thanks for doing it so quickly!
