### ISSUE TITLE
Accessing request object within component class?

### ISSUE THREAD

**Issue by jdrempel** [adamghill/django-unicorn#73]
Hi there,

I'm not quite sure how I should go about accessing the request object associated with the UnicornView?

Saying `u = self.request.user`, for instance, gives the exception:

> AttributeError: 'NoneType' object has no attribute 'user'

**Comment by adamghill** [comment]
That's a good question! It looks like I don't set `request` on the components currently, but I can for the next update.

For the initial rendering of the component I have access to the page request. However, I'm not sure what `request` you would expect when the component gets updates? I have access to the AJAX request where the component gets updated which might make the most sense -- is that what you would expect to happen?

**Comment by jdrempel** [comment]
To be honest I'm not quite sure - I haven't had much experience using `django-unicorn` so far, so I can't confidently say if that would make sense for my use cases. But, from my experience with Django I'd say that what you proposed makes sense. 
I look forward to the next update! Keep up the great work, this is a very handy tool!

**Comment by adamghill** [comment]
Thanks! This has been tagged with 0.10.0 which just got released to pypi. I'll update the documentation site soon as well. But, feel free to try it out and let me know if you run into any problems.

**Comment by adamghill** [comment]
Now documented here: https://www.django-unicorn.com/documentation/components/advanced#instance-properties.
