### ISSUE TITLE
Event bindings breaking

### ISSUE THREAD

**Issue by jdrempel** [adamghill/django-unicorn#85]
Hi there,

I've got a jQuery on("click") event handler set for a specific kind of button within the django-unicorn view. I'm using django-unicorn for a typeahead search, and each of the search results has one of these buttons ("Delete") attached. Clicking the button should show a Bootstrap modal and it should trigger the event handler `initDelete()` which should populate the modal with some content related to the search result for which the button was pressed. The code below shows `initDelete()`:

```python3
function initDelete() {

    $("#unicorn-wrapper").on("click", ".activate-delete", function() {

        var item_id = $(this).val();
        var item_name = $(this).data('itemname');
        console.log(item_name + " " + item_id);

        $("#delete-which-item").text(item_name);
        $("#confirm-item-delete").val(item_id);

    });
}
```

This works fine immediately after the page (and unicorn component) loads. However, entering a search query causes things to get... weird. After entering a query and narrowing down the results, clicking the delete button, the modal window gets populated with information from a completely different search result. For example:

Initial result list:
```
Item 1 (delete)
Item 2 (delete)
Item 3 (delete)
```
Type in: "2"
Results narrow to show only Item 2.
Click "delete" for Item 2.
Modal window is populated with information about Item 1.

The strange part is that using the debug menu inspector shows that *all of the values for Item 2's delete button are in fact correct* (i.e. the `data-itemname` and `value`). So I assume somehow the script is getting passed information from a previous version of the DOM? If that's the case, do you know how I would get around it? Or is this a question I should be asking over at the `morphdom` issues board?

**Comment by adamghill** [comment]
Hey thanks for the issue! Sorry you ran into this issue -- honestly, I haven't dealt with unicorn interacting with other JS libraries that much, yet.

I'm guessing this has to do more with how the unicorn JS interacts with other libraries or event delegation than strictly a `morphdom` issue. What would be super helpful to me is if you could create a PR and add an example of the issue to my `example` Django project. Or another option would be to write a Javascript test with `ava` that demonstrates the problem. You can see examples in the `tests/js/` folder.

I'll try to diagnose the problem without it, but it would save some time if I had a test case that I can verify any fixes easily.

**Comment by jdrempel** [comment]
> What would be super helpful to me is if you could create a PR and add an example of the issue to my `example` Django project.

Will do.

**Comment by jdrempel** [comment]
I've been unable to replicate the issue in the example project so I'll continue investigating in my own project and see if I can identify where the problem lies.

**Comment by adamghill** [comment]
Ok, that would be great! Thanks.
